### ISSUE TITLE
Error with import liana

### ISSUE THREAD

**Issue by inofechm** [saezlab/liana-py#10]
Hi I updated to the new release of liana-py 0.1.7
and am getting an error with import liana, I did not have this error with the previous release on the same system and python environment

Python 3.7.2 (default, Dec 18 2019, 16:55:18) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import liana
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.mounts/labs/abelsonlab/public/Ido/python_venvs/liana_venv/lib/python3.7/site-packages/liana/__init__.py", line 4, in <module>
    from liana import method as mt, plotting as pl, resource as rs, utils as ut, multi as mu, funcomics as fun
  File "/.mounts/labs/abelsonlab/public/Ido/python_venvs/liana_venv/lib/python3.7/site-packages/liana/method/__init__.py", line 1, in <module>
    from ._Method import Method, MethodMeta, _show_methods
  File "/.mounts/labs/abelsonlab/public/Ido/python_venvs/liana_venv/lib/python3.7/site-packages/liana/method/_Method.py", line 133
    for sample in (progress_bar := tqdm(samples, disable=not verbose)):
                                ^
SyntaxError: invalid syntax

**Comment by dbdimitrov** [comment]
Hi @inofechm,

This might be a python version issue because of the walrus assignment. (It requires Python>=3.8).

I will double check and I can change it to something that works on 3.7

**Comment by dbdimitrov** [comment]
Hi @inofechm,

I tried on both 3.7.12 and 3.7.2 and wasn't able to reproduce your error on either.
Can you try setting up a new conda env, and let me know if you still encounter it.

I can remove the walrus operator, but need to confirm if this is the issue first.

**Comment by inofechm** [comment]
Hi Daniel,
Weird I am still getting the error with a new virtual environment...
I'm not sure I can confirm whether its the walrus operator other than the walrus operator only being added to python in 3.8.

I'm just going to upgrade our HPC's python version.
Thanks for the help

**Comment by dbdimitrov** [comment]
Hi @inofechm,

I have now removed the walrus assignment on the GH version, you can maybe try installing liana via:
pip install git+https://github.com/saezlab/liana-py

Hope this works!

**Comment by inofechm** [comment]
Thanks it works now!
