### ISSUE TITLE
MOFA talk with multiple samples

### ISSUE THREAD

**Issue by nicolebussola** [saezlab/liana-py#101]
HI! First of all thanks for this great tool. I am trying to use LIANA to find CCC on a dataset with one condition but multiple samples. Thus,  I am referring to the MOFAtalk tutorial (am I right?). However, when I try to create a multi-view structure with `lrs_to_view`
and my `sample_key` (`pt`) I get the following error:

**Screenshots**
![image](https://github.com/saezlab/liana-py/assets/31658006/84473aac-9639-4fee-9136-ed2a5c987610)

**Comment by dbdimitrov** [comment]
Hi @nicolebussola,

Thanks for using LIANA :) I assume the error that you're getting has to do with the data that you are passing being a view rather than a copy. Perhaps, you could add .copy() when you subset to blood filt?

Let me know if this works!

Daniel
