### ISSUE TITLE
Clarify LIANA + MOFA vignette

### ISSUE THREAD

**Issue by dbdimitrov** [saezlab/liana-py#102]
- pass `sample_key` explicitly
- be explicit about `resource_name`
- `samples_per_view` - somehow make this more obvious?

**Comment by decusInLabore** [comment]
Perhaps automatically reduce the 'samples_per_view' default parameter if mandated by the dataset structure. Alternatively, add a comment in the vignette.

**Comment by decusInLabore** [comment]
In the vignette, review the resource_name = "mouseconsensus",
