### ISSUE TITLE
Please check if appropriate organism/ID type was provided! Allowed proportion (0.98) of missing resource elements exceeded (1.00).

### ISSUE THREAD

**Issue by soniyalama** [saezlab/liana-py#105]
When running this, I get the error above: 
`cellphonedb(adata, groupby='cluster_labels', expr_prop=0.1, resource_name='mouseconsensus', verbose=True, key_added='cpdb_res')`

My adata contains the gene names, the normalised SCT assay (layer = data) as required, and the barcodes. 
My dataset is mouse data and so here, I'm using the mouse consensus. 

Another question, what if I want to run it through connectome, which value for the  "key_added" parameter should I use? 

Thanks in advance.

**Comment by soniyalama** [comment]
To be more specific, this is the error I got 
@dbdimitrov 
 --------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[44], line 2
      1 # run cellphonedb
----> 2 cellphonedb(adata, groupby='cluster_labels', expr_prop=0.1, resource_name='mouseconsensus', verbose=True, key_added='cpdb_res')

File [/data/leuven/345/vsc34524/miniconda3/envs/liana/lib/python3.10/site-packages/liana/method/sc/_Method.py:250](https://ondemand.hpc.kuleuven.be/data/leuven/345/vsc34524/miniconda3/envs/liana/lib/python3.10/site-packages/liana/method/sc/_Method.py#line=249), in Method.__call__(self, adata, groupby, resource_name, expr_prop, min_cells, groupby_pairs, base, supp_columns, return_all_lrs, key_added, use_raw, layer, de_method, n_perms, seed, n_jobs, resource, interactions, mdata_kwargs, inplace, verbose)
    247 else:
    248     ad = adata
--> 250 liana_res = liana_pipe(adata=ad,
    251                        groupby=groupby,
    252                        resource_name=resource_name,
    253                        resource=resource,
    254                        interactions=interactions,
    255                        expr_prop=expr_prop,
    256                        min_cells=min_cells,
    257                        supp_columns=supp_columns,
    258                        return_all_lrs=return_all_lrs,
    259                        groupby_pairs=groupby_pairs,
    260                        base=base,
    261                        de_method=de_method,
    262                        verbose=verbose,
    263                        _score=self._method,
    264                        n_perms=n_perms,
    265                        seed=seed,
    266                        n_jobs=n_jobs,
    267                        use_raw=use_raw,
    268                        layer=layer,
    269                        )
    270 if inplace:
    271     adata.uns[key_added] = liana_res

File [/data/leuven/345/vsc34524/miniconda3/envs/liana/lib/python3.10/site-packages/liana/method/sc/_liana_pipe.py:143](https://ondemand.hpc.kuleuven.be/data/leuven/345/vsc34524/miniconda3/envs/liana/lib/python3.10/site-packages/liana/method/sc/_liana_pipe.py#line=142), in liana_pipe(adata, groupby, resource_name, resource, interactions, groupby_pairs, expr_prop, min_cells, base, de_method, n_perms, seed, verbose, use_raw, n_jobs, layer, supp_columns, return_all_lrs, _score, _methods, _consensus_opts, _aggregate_method)
    140 resource = explode_complexes(resource)
    142 # Check overlap between resource and adata
--> 143 assert_covered(np.union1d(np.unique(resource[P.ligand]),
    144                           np.unique(resource[P.receptor])),
    145                adata.var_names, verbose=verbose)
    147 # Filter Resource
    148 resource = filter_resource(resource, adata.var_names)

File [/data/leuven/345/vsc34524/miniconda3/envs/liana/lib/python3.10/site-packages/liana/method/_pipe_utils/_pre.py:60](https://ondemand.hpc.kuleuven.be/data/leuven/345/vsc34524/miniconda3/envs/liana/lib/python3.10/site-packages/liana/method/_pipe_utils/_pre.py#line=59), in assert_covered(subset, superset, subset_name, superset_name, prop_missing_allowed, verbose)
     53 if prop_missing > prop_missing_allowed:
     54     msg = (
     55         f"Please check if appropriate organism[/ID](https://ondemand.hpc.kuleuven.be/ID) type was provided! "
     56         f"Allowed proportion ({prop_missing_allowed}) of missing "
     57         f"{subset_name} elements exceeded ({prop_missing:.2f}). "
     58         f"Too few features from the resource were found in the data."
     59     )
---> 60     raise ValueError(msg + f" [{x_missing}] missing from {superset_name}")
     62 _logg(f"{prop_missing:.2f} of entities in the resource are missing from the data.", verbose=verbose & (prop_missing > 0))

ValueError: Please check if appropriate organism[/ID](https://ondemand.hpc.kuleuven.be/ID) type was provided! Allowed proportion (0.98) of missing resource elements exceeded (1.00). Too few features from the resource were found in the data. [A2m, Aanat, Abca1, Ace, Ackr2, Ackr3, Ackr4, Actr2, Acvr1, Acvr1b, Acvr1c, Acvr2a, Acvr2b, Acvrl1, Ada, Adam10, Adam11, Adam12, Adam15, Adam17, Adam2, Adam22, Adam23, Adam28, Adam29, Adam7, Adam9, Adamts3, Adcy1, Adcy7, Adcy8, Adcy9, Adcyap1, Adcyap1r1, Adipoq, Adipor1, Adipor2, Adm, Adm2, Ado, Adora1, Adora2a, Adora2b, Adora3, Adra2a, Adra2b, Adrb1, Adrb2, Adrb3, Ager, Agr2, Agrn, Agrp, Agt, Agtr1a, Agtr2, Ahsg, Aimp1, Alb, Alcam, Alk, Alox5, Ambn, Amelx, Amfr, Amh, Amhr2, Ang, Angpt1, Angpt2, Angpt4, Angptl1, Angptl2, Angptl3, Angptl4, Angptl7, Antxr1, Anxa1, Anxa2, Apcdd1, Apln, Aplnr, Aplp1, Aplp2, Apoa1, Apoa2, Apoa4, Apob, Apoc2, Apoc4, Apod, Apoe, Apoo, App, Aqp1, Aqp5, Ar, Areg, Arf1, Arf6, Arpc5, Art1, Artn, Asgr1, Asgr2, Atp1a3, Atp6ap2, Atrn, Avp, Avpr1a, Avpr1b, Avpr2, Axl, Azgp1, B2m, Bambi, Bcam, Bcan, Bdkrb1, Bdkrb2, Bdnf, Bgn, Bmp1, Bmp10, Bmp15, Bmp2, Bmp3, Bmp4, Bmp5, Bmp6, Bmp7, Bmp8a, Bmpr1a, Bmpr1b, Bmpr2, Boc, Bpi, Brs3, Bsg, Bst1, Btc, Btla, Btn1a1, C1qa, C1qb, C1qbp, C1qtnf1, C1qtnf5, C3, C3ar1, C4a, C4b, C5ar1, C5ar2, C920025E04Rik, Cacna1c, Cadm1, Cadm3, Calca, Calcr, Calcrl, Calml3, Calr, Camp, Cap1, Catsper1, Cav1, Ccbe1, Cck, Cckar, Cckbr, Ccl1, Ccl11, Ccl12, Ccl17, Ccl2, Ccl20, Ccl21b, Ccl22, Ccl24, Ccl25, Ccl27b, Ccl28, Ccl4, Ccl5, Ccr1, Ccr10, Ccr2, Ccr3, Ccr4, Ccr5, Ccr6, Ccr7, Ccr8, Ccr9, Ccrl2, Cd14, Cd151, Cd163, Cd177, Cd180, Cd19, Cd2, Cd200, Cd200r1, Cd200r2, Cd200r4, Cd209a, Cd209e, Cd22, Cd226, Cd244, Cd247, Cd248, Cd27, Cd274, Cd28, Cd300lf, Cd34, Cd36, Cd38, Cd3d, Cd3g, Cd4, Cd40, Cd40lg, Cd44, Cd46, Cd47, Cd48, Cd5, Cd53, Cd59b, Cd5l, Cd6, Cd63, Cd68, Cd69, Cd7, Cd70, Cd72, Cd74, Cd79a, Cd80, Cd81, Cd82, Cd86, Cd8a, Cd8b1, Cd9, Cd93, Cdh1, Cdh10, Cdh11, Cdh2, Cdh5, Cdh7, Cdon, Ceacam1, Ceacam16, Ceacam19, Ceacam2, Cel, Celsr1, Celsr2, Celsr3, Cer1, Cfc1, Cfh, Cfp, Cftr, Cga, Cgn, Chad, Chl1, Chrm1, Chrm3, Chrna10, Chrna3, Chrna4, Chrna7, Chrna9, Chrnb2, Chrnb4, Cirbp, Cklf, Clcf1, Cldn4, Clec10a, Clec11a, Clec12a, Clec14a, Clec1b, Clec3a, Clec4g, Cmklr1, Cnr1, Cnr2, Cntf, Cntfr, Cntn1, Cntn2, Cntn3, Cntn4, Cntn5, Cntn6, Cntnap1, Col10a1, Col11a1, Col11a2, Col12a1, Col13a1, Col14a1, Col15a1, Col16a1, Col18a1, Col19a1, Col1a1, Col1a2, Col20a1, Col22a1, Col24a1, Col26a1, Col27a1, Col28a1, Col2a1, Col3a1, Col4a1, Col4a2, Col4a3, Col4a4, Col4a5, Col4a6, Col5a1, Col5a2, Col5a3, Col6a1, Col6a2, Col6a3, Col6a5, Col6a6, Col7a1, Col8a1, Col8a2, Col9a1, Col9a2, Col9a3, Colq, Comp, Copa, Cort, Cp, Cr2, Crh, Crhr1, Crhr2, Crisp2, Crlf1, Crlf2, Crlf3, Crp, Crtam, Csf1, Csf1r, Csf2, Csf2ra, Csf2rb, Csf3, Csf3r, Cspg4, Ctf1, Cthrc1, Ctla4, Cubn, Cx3cl1, Cx3cr1, Cxcl1, Cxcl10, Cxcl12, Cxcl13, Cxcl14, Cxcl16, Cxcl17, Cxcl2, Cxcl5, Cxcr1, Cxcr2, Cxcr3, Cxcr4, Cxcr5, Cxcr6, Cytl1, Dag1, Dcbld2, Dcc, Dchs1, Dclk3, Dcn, Ddr1, Ddr2, Dhh, Dip2a, Dkk1, Dkk2, Dkk3, Dkk4, Dlk1, Dlk2, Dll1, Dll3, Dll4, Dmp1, Dnajb11, Dpp4, Draxin, Drd2, Drd4, Dsc1, Dsc2, Dsc3, Dscam, Dsg1a, Dsg1b, Dsg2, Dsg3, Dsg4, Dysf, Ear11, Ear5, Ebi3, Ecm1, Edil3, Edn1, Edn2, Edn3, Ednra, Ednrb, Efemp1, Efemp2, Efna1, Efna2, Efna3, Efna4, Efna5, Efnb1, Efnb2, Efnb3, Egf, Egfr, Enam, Eng, Enho, Eno1, Enpep, Entpd1, Epgn, Epha1, Epha10, Epha2, Epha3, Epha4, Epha5, Epha6, Epha7, Epha8, Ephb1, Ephb2, Ephb3, Ephb4, Ephb6, Epo, Epor, Erap1, Erbb2, Erbb3, Erbb4, Ereg, Esam, Etv5, F10, F11, F11r, F12, F13a1, F2, F2r, F2rl1, F2rl2, F2rl3, F3, F7, F8, F9, Fabp5, Fadd, Fam3b, Fam3c, Fap, Farp2, Fas, Fasl, Fat4, Fbln1, Fbln2, Fbn1, Fcer1a, Fcer2a, Fcgr3, Fcgr4, Fcgrt, Ffar2, Fga, Fgb, Fgf1, Fgf10, Fgf11, Fgf12, Fgf13, Fgf14, Fgf15, Fgf16, Fgf17, Fgf18, Fgf2, Fgf20, Fgf21, Fgf22, Fgf23, Fgf3, Fgf4, Fgf5, Fgf6, Fgf7, Fgf8, Fgf9, Fgfr1, Fgfr2, Fgfr3, Fgfr4, Fgfrl1, Fgg, Fgl1, Flot1, Flrt3, Flt1, Flt3, Flt3l, Flt4, Fn1, Fndc5, Fpr1, Fpr2, Fras1, Frem1, Frem2, Frs3, Fshb, Fshr, Fst, Fstl1, Fstl5, Fxyd6, Fzd1, Fzd10, Fzd2, Fzd3, Fzd4, Fzd5, Fzd6, Fzd7, Fzd8, Fzd9, Gabbr2, Gad1, Gal, Galp, Galr1, Galr2, Galr3, Gas1, Gas6, Gast, Gc, Gcgr, Gdf1, Gdf10, Gdf11, Gdf15, Gdf2, Gdf3, Gdf5, Gdf6, Gdf7, Gdf9, Gdnf, Gfra1, Gfra2, Gfra3, Gfra4, Gfral, Gh, Ghr, Ghrh, Ghrhr, Ghrl, Ghsr, Gip, Gipr, Gjb2, Glg1, Glp1r, Glra2, Gm11127, Gm13305, Gm13306, Gm2002, Gm2023, Gm2506, Gm3934, Gm5506, Gm7030, Gnai2, Gnas, Gnb3, Gnrh1, Gnrhr, Gp1ba, Gp1bb, Gp49a, Gp5, Gp6, Gp9, Gpc1, Gpc2, Gpc3, Gpc4, Gpc5, Gpha2, Gphb5, Gpi1, Gpnmb, Gpr135, Gpr151, Gpr152, Gpr171, Gpr182, Gpr19, Gpr20, Gpr25, Gpr35, Gpr37, Gpr37l1, Gpr39, Gpr44, Gpr75, Gpr83, Gpr84, Gprc5d, Gprc6a, Grem1, Grem2, Grin2a, Grin2b, Grin2c, Grin2d, Grm1, Grm4, Grm5, Grm7, Grn, Grp, Grpr, Gstm7, Gsto1, Gstp1, Gstp2, Guca2a, Guca2b, Gucy2c, Gucy2e, Gzma, H2-Aa, H2-Ab1, H2-DMa, H2-DMb1, H2-DMb2, H2-Ea-ps, H2-Eb1, H2-K1, H2-M3, H2-Ob, H2-T23, Hapln1, Has2, Havcr2, Hbegf, Hc, Hcrt, Hcrtr1, Hcrtr2, Hdc, Hebp1, Hfe, Hgf, Hhip, Hmmr, Hp, Hpx, Hras, Hrh1, Hrh2, Hrh3, Hrh4, Hsp90aa1, Hsp90b1, Hspa1a, Hspa4, Hspa8, Hspg2, Htr1a, Htr1b, Htr1d, Htr1f, Htr2a, Htr2b, Htr2c, Htr4, Htr5a, Htr6, Htr7, Iapp, Ibsp, Icam1, Icam2, Icam4, Icam5, Icos, Icosl, Ifna11, Ifnar1, Ifnar2, Ifnb1, Ifne, Ifng, Ifngr1, Ifngr2, Ifnk, Ifnlr1, Igdcc3, Igdcc4, Igf1, Igf1r, Igf2, Igf2r, Igfbp4, Igfbpl1, Igfl3, Igflr1, Igsf1, Igsf10, Ihh, Il10, Il10ra, Il10rb, Il11, Il11ra1, Il11ra2, Il12a, Il12b, Il12rb1, Il12rb2, Il13, Il13ra1, Il13ra2, Il15, Il15ra, Il16, Il17a, Il17b, Il17c, Il17f, Il17ra, Il17rb, Il17rc, Il17re, Il18, Il18bp, Il18r1, Il18rap, Il19, Il1a, Il1b, Il1f10, Il1f5, Il1f6, Il1f8, Il1f9, Il1r1, Il1r2, Il1rap, Il1rapl1, Il1rapl2, Il1rl1, Il1rl2, Il1rn, Il2, Il20, Il20ra, Il20rb, Il21, Il21r, Il22, Il22ra1, Il22ra2, Il23a, Il23r, Il24, Il25, Il27, Il27ra, Il2ra, Il2rb, Il2rg, Il33, Il34, Il3ra, Il4, Il4ra, Il5, Il5ra, Il6, Il6ra, Il6st, Il7, Il7r, Il9, Il9r, Iltifb, Impg2, Inha, Inhba, Inhbb, Inhbc, Inhbe, Ins2, Insl3, Insl5, Insr, Irak4, Islr2, Itga1, Itga10, Itga11, Itga2, Itga2b, Itga3, Itga4, Itga5, Itga6, Itga7, Itga8, Itga9, Itgad, Itgae, Itgal, Itgam, Itgav, Itgax, Itgb1, Itgb2, Itgb3, Itgb3bp, Itgb4, Itgb5, Itgb6, Itgb7, Itgb8, Itih2, Izumo1, Jag1, Jag2, Jam2, Jam3, Jmjd6, Kcna3, Kcnd1, Kcnd2, Kcnj10, Kcnj15, Kcnj4, Kcnq1, Kdr, Kel, Kidins220, Kiss1, Kiss1r, Kit, Kitl, Kl, Klb, Klk1b8, Klrb1a, Klrb1b, Klrb1c, Klrc1, Klrd1, Klrg1, Klrg2, Kng1, Kng2, Kremen1, Kremen2, L1cam, LOC100861969, LOC100861978, Lag3, Lair1, Lama1, Lama2, Lama3, Lama4, Lama5, Lamb1, Lamb2, Lamb3, Lamc1, Lamc2, Lamc3, Lamp1, Lamp2, Lck, Lcn2, Ldlr, Leap2, Lefty1, Lefty2, Lep, Lepr, Lgals1, Lgals3, Lgals3bp, Lgals8, Lgi1, Lgi2, Lgi3, Lgi4, Lgr4, Lgr5, Lgr6, Lhb, Lhcgr, Lif, Lifr, Lilrb4, Lin7c, Lingo1, Lipc, Liph, Lman1, Lmbr1l, Lpar1, Lpar2, Lpar3, Lpar4, Lpl, Lpp, Lrig1, Lrig2, Lrp1, Lrp10, Lrp11, Lrp1b, Lrp2, Lrp4, Lrp5, Lrp6, Lrp8, Lrpap1, Lrrc4, Lrrc4b, Lrrc4c, Lrrn3, Lrrtm2, Lsr, Lta, Ltb, Ltbp1, Ltbp3, Ltbr, Ltf, Lum, Ly86, Ly96, Lypd3, Lyve1, Lyz1, Lyz2, Mag, Maged1, Marco, Mas1, Matn1, Mbl2, Mc1r, Mc2r, Mc3r, Mc4r, Mc5r, Mcam, Mcfd2, Mchr1, Mdk, Megf10, Mepe, Mertk, Met, Mfap2, Mfap3l, Mfap5, Mfge8, Mfng, Mfrp, Mgl2, Mgrn1, Mia, Mif, Mmp12, Mmp13, Mmp1a, Mmp2, Mmp24, Mmp7, Mmp9, Mmrn2, Mog, Mpl, Mpz, Mpzl1, Mrap, Mrc1, Mrc2, Mrgprb1, Mrgprb2, Mrgprx2, Msmp, Mst1, Mst1r, Mstn, Mtnr1a, Mtnr1b, Mttp, Muc2, Muc5ac, Muc6, Musk, Myl9, Myoc, Nampt, Ncam1, Ncam2, Ncan, Ncl, Ncr1, Ncstn, Ndp, Negr1, Nell2, Neo1, Nfasc, Ngf, Ngfr, Nid1, Nlgn1, Nlgn2, Nlgn3, Nmb, Nmbr, Nms, Nmu, Nmur1, Nmur2, Nodal, Notch1, Notch2, Notch3, Notch4, Npb, Npbwr1, Npff, Npffr1, Npffr2, Npnt, Nppa, Nppc, Npr1, Npr2, Npr3, Nps, Npsr1, Nptx1, Nptx2, Nptxr, Npvf, Npw, Npy, Npy1r, Npy2r, Npy5r, Nr0b2, Nrcam, Nrg2, Nrg3, Nrg4, Nrp1, Nrp2, Nrsn1, Nrtn, Nrxn1, Nrxn2, Nt5e, Ntf3, Ntf5, Ntn1, Ntn3, Ntn4, Ntng1, Ntng2, Ntrk1, Ntrk2, Ntrk3, Nts, Ntsr1, Ntsr2, Nucb2, Nxph1, Nxph2, Nxph3, Ocln, Ogfr, Oit1, Olfm2, Olr1, Omg, Oprd1, Oprk1, Oprl1, Oprm1, Orai2, Osm, Osmr, Ostn, Oxt, Oxtr, P2rx7, P2ry12, P2ry14, P2ry6, P4hb, Pam, Pard3, Pcsk1n, Pcsk9, Pdap1, Pdcd1, Pdcd1lg2, Pdcd2, Pdgfa, Pdgfb, Pdgfc, Pdgfd, Pdgfra, Pdgfrb, Pdpn, Pdx1, Pdyn, Pecam1, Penk, Pf4, Pgf, Pglyrp1, Phex, Pi16, Piga, Pigf, Pigr, Pip, Pirb, Pkm, Pla2g10, Pla2r1, Plat, Plau, Plaur, Pld1, Pld2, Plg, Plgrkt, Plscr1, Plscr4, Pltp, Plxdc1, Plxdc2, Plxna1, Plxna2, Plxna3, Plxna4, Plxnb1, Plxnb2, Plxnb3, Plxnc1, Plxnd1, Pmch, Pnoc, Podxl2, Pomc, Postn, Ppy, Prl, Prlh, Prlhr, Prlr, Prn, Prnd, Proc, Procr, Prok1, Prok2, Prokr1, Prokr2, Pros1, Prss2, Prtg, Psap, Psen1, Pspn, Ptch1, Ptch2, Ptdss1, Ptgdr, Ptger2, Ptger3, Ptger4, Ptgir, Ptgs2, Pth, Pth1r, Pth2, Pth2r, Pthlh, Ptk7, Ptn, Ptpn6, Ptpra, Ptprb, Ptprc, Ptprf, Ptprg, Ptprj, Ptprk, Ptprm, Ptprr, Ptprs, Ptpru, Ptprz1, Pyy, Qdpr, Qrfp, Qrfpr, Ramp1, Ramp2, Ramp3, Rarres1, Rarres2, Rbp3, Rbp4, Reck, Reln, Ren1, Ret, Retn, Rgma, Rgmb, Rhag, Rhbdf2, Rhbdl2, Rims1, Rims2, Ripk1, Rln1, Rln3, Rnf43, Robo1, Robo2, Robo3, Robo4, Ror1, Ror2, Rps19, Rpsa, Rspo1, Rspo2, Rspo3, Rspo4, Rtn4, Rtn4r, Rtn4rl1, Rxfp1, Rxfp2, Rxfp3, Rxfp4, Rxra, Ryk, Ryr1, Ryr2, S100a1, S100a10, S100a4, S100a8, S100a9, S100b, S1pr1, S1pr2, S1pr3, S1pr4, S1pr5, Saa1, Saa2, Scara5, Scarb1, Scarf1, Scel, Scgb1a1, Scgb3a1, Scgb3a2, Scn5a, Scn8a, Sctr, Scube2, Sdc1, Sdc2, Sdc3, Sdc4, Sdk2, Sectm1a, Sele, Sell, Selp, Selplg, Sema3a, Sema3b, Sema3c, Sema3d, Sema3e, Sema3f, Sema3g, Sema4a, Sema4b, Sema4c, Sema4d, Sema4f, Sema4g, Sema5a, Sema5b, Sema6a, Sema6b, Sema6d, Sema7a, Serpina1a, Serpina1b, Serpina1c, Serpina1d, Serpina1e, Serpina7, Serpinc1, Serpine1, Serpine2, Serpinf1, Serping1, Sertad1, Sfrp1, Sfrp2, Sftpa1, Sftpd, Shank1, Shank2, Shbg, Shh, Sigirr, Siglec1, Sirpa, Slamf9, Slc16a1, Slc16a2, Slc16a7, Slc17a7, Slc18a2, Slc18a3, Slc2a2, Slc37a1, Slc40a1, Slc4a11, Slc6a8, Slit1, Slit2, Slit3, Slitrk1, Slitrk2, Slitrk3, Slitrk6, Slpi, Slurp1, Smap1, Smo, Snca, Snx14, Socs2, Sorbs1, Sorcs2, Sorcs3, Sorl1, Sort1, Sost, Sostdc1, Sparc, Spink3, Spint1, Spn, Spon1, Spon2, Spp1, Sptan1, Sptbn2, Sst, Sstr1, Sstr2, Sstr3, Sstr4, Sstr5, St14, St6gal1, Stab1, Stab2, Stra6, Stx1a, Stx3, Stx4a, Tac1, Tac2, Tacr1, Tacr2, Tacr3, Tarm1, Tbxa2r, Tcn2, Tctn1, Tdgf1, Tecta, Tectb, Tek, Tff1, Tff2, Tff3, Tfpi, Tfr2, Tfrc, Tg, Tgfa, Tgfb1, Tgfb2, Tgfb3, Tgfbr1, Tgfbr2, Tgfbr3, Tgm2, Tgs1, Thbd, Thbs1, Thbs2, Thbs3, Thbs4, Thpo, Thy1, Tie1, Timp1, Timp2, Timp3, Tln1, Tlr1, Tlr2, Tlr4, Tlr6, Tlr7, Tlr9, Tmed5, Tmem219, Tmem67, Tnc, Tnf, Tnfrsf10b, Tnfrsf11a, Tnfrsf11b, Tnfrsf12a, Tnfrsf13b, Tnfrsf13c, Tnfrsf14, Tnfrsf17, Tnfrsf18, Tnfrsf19, Tnfrsf1a, Tnfrsf1b, Tnfrsf21, Tnfrsf25, Tnfrsf4, Tnfrsf8, Tnfsf10, Tnfsf11, Tnfsf12, Tnfsf13, Tnfsf13b, Tnfsf14, Tnfsf15, Tnfsf18, Tnfsf4, Tnfsf8, Tnn, Tnr, Tnxb, Tph1, Tpo, Tpsb2, Tradd, Traf2, Traf3, Trem1, Trem2, Treml2, Trf, Trh, Trhr, Trpm2, Trpm3, Trpv1, Trpv6, Try10, Try4, Try5, Tshb, Tshr, Tslp, Tspan1, Tspan10, Tspan12, Tspan14, Tspan15, Tspan17, Tspan5, Ttr, Txlna, Tyro3, Tyrobp, Ucn, Ucn2, Ucn3, Unc5a, Unc5b, Unc5c, Unc5d, Uts2, Uts2b, Uts2r, Vangl2, Vasn, Vasp, Vcam1, Vcan, Vcl, Vegfa, Vegfb, Vegfc, Vgf, Vim, Vip, Vipr1, Vipr2, Vldlr, Vsig10l, Vtn, Vwf, Wfikkn2, Wif1, Wnt1, Wnt10a, Wnt10b, Wnt11, Wnt16, Wnt2, Wnt2b, Wnt3, Wnt3a, Wnt4, Wnt5a, Wnt5b, Wnt6, Wnt7a, Wnt7b, Wnt8a, Wnt8b, Wnt9a, Wnt9b, Xcl1, Xcr1, Ybx1, Znrf3, Zp3, a] missing from var_names

**Comment by dbdimitrov** [comment]
Hi @soniyalama,

Given that LIANA does not find those genesymbols, it might be best to check that your `adata.var.index` contains them.

re running connectome: they `key_added` adds the results dataframe to the `adata.uns[key_added]` slot, you should use the connectome method (also imported in the tutorial) to run connectome.

**Comment by soniyalama** [comment]
Hi @dbdimitrov, 
Thank you for your reply. 

Well, we've checked for overlap between both the mouse consensus genes and my own genes and there is an overlap of 1203 genes. So I'm not sure what is creating the issue here? 

Kind regards, 
Soniya Lama

**Comment by dbdimitrov** [comment]
Hi @soniyalama, this is strange - if the `var_names` overlap with the resource, it should work. I could double-check if you provide a small subset of your data.

**Comment by soniyalama** [comment]
this is my adata.obs subset: 
`                          orig.ident  nCount_RNA  nFeature_RNA    label  \
barcode                                                                    
3763_01__AAACCCAAGTGGTTGG        3763        1836           883  3763_01   
3763_01__AAACGAATCCTGTAAG        3763        3143          1057  3763_01   
3763_01__AAACGCTAGACTACGG        3763        2012          1152  3763_01   
3763_01__AAACGCTAGCGCCTCA        3763        1920           866  3763_01   
3763_01__AAAGAACAGCGTGAAC        3763        3325          1302  3763_01   

                           sample  percent_mt_genes  nCount_SCT  nFeature_SCT  \
barcode                                                                         
3763_01__AAACCCAAGTGGTTGG       1          3.921569        3540           912   
3763_01__AAACGAATCCTGTAAG       1          3.086223        3592          1057   
3763_01__AAACGCTAGACTACGG       1          2.137177        3271          1160   
3763_01__AAACGCTAGCGCCTCA       1          1.770833        3415           893   
3763_01__AAAGAACAGCGTGAAC       1          3.639098        3632          1302   

                          doublet_status            group_label tcell_group  \
barcode                                                                       
3763_01__AAACCCAAGTGGTTGG        singlet  T-cell.TBI-Micro.Sham         TBI   
3763_01__AAACGAATCCTGTAAG        singlet  T-cell.TBI-Micro.Sham         TBI   
3763_01__AAACGCTAGACTACGG        singlet  T-cell.TBI-Micro.Sham         TBI   
3763_01__AAACGCTAGCGCCTCA        singlet  T-cell.TBI-Micro.Sham         TBI   
3763_01__AAAGAACAGCGTGAAC        singlet  T-cell.TBI-Micro.Sham         TBI   

                          micro_group     treatment  seurat_clusters  \
barcode                                                                
3763_01__AAACCCAAGTGGTTGG        Sham  PHP.GFAP-GFP               11   
3763_01__AAACGAATCCTGTAAG        Sham  PHP.GFAP-GFP               28   
3763_01__AAACGCTAGACTACGG        Sham  PHP.GFAP-GFP               10   
3763_01__AAACGCTAGCGCCTCA        Sham  PHP.GFAP-GFP                9   
3763_01__AAAGAACAGCGTGAAC        Sham  PHP.GFAP-GFP                6   

                                             barcode    UMAP_1     UMAP_2  \
barcode                                                                     
3763_01__AAACCCAAGTGGTTGG  3763_01__AAACCCAAGTGGTTGG  6.795611   8.890237   
3763_01__AAACGAATCCTGTAAG  3763_01__AAACGAATCCTGTAAG  9.122911   7.617782   
3763_01__AAACGCTAGACTACGG  3763_01__AAACGCTAGACTACGG -6.704934  -1.941374   
3763_01__AAACGCTAGCGCCTCA  3763_01__AAACGCTAGCGCCTCA  7.340573  10.868954   
3763_01__AAAGAACAGCGTGAAC  3763_01__AAAGAACAGCGTGAAC  6.393289   7.908899   

                            cluster_labels  
barcode                                     
3763_01__AAACCCAAGTGGTTGG             CD8+  
3763_01__AAACGAATCCTGTAAG             CD8+  
3763_01__AAACGCTAGACTACGG  Homeo Microglia  
3763_01__AAACGCTAGCGCCTCA             CD8+  
3763_01__AAAGAACAGCGTGAAC             CD8+`


this is my adata.var_names. I put them in a csv (it's also a subset)
[gene_subset.csv](https://github.com/saezlab/liana-py/files/15154941/gene_subset.csv)

Thanks for your help!

**Comment by dbdimitrov** [comment]
Hi @soniyalama,

It seems like you are passing the .raw instead of X, and your .raw adata has numbers instead of gene names in `.var`. 

It should work if you pass `use_raw=False`:
`li.mt.cellphonedb(adata, groupby='group_label', expr_prop=0, resource_name='mouseconsensus', verbose=True, use_raw=False)`

**Comment by dbdimitrov** [comment]
I plan to change `use_raw` to be False by default in future version as it seems now that the preferred approach is just using layers. Hope this helps.

**Comment by soniyalama** [comment]
Hi Mr. Dimitrov,

This seems to resolve the issue. Thanks a lot. Another question I had if it's correct that the tool is running on the SCT assay, layer counts? This wasn't specified, and I'm not pretty well known. 

Kind regards, 
Soniya Lama.

**Comment by dbdimitrov** [comment]
@soniyalama as long as the cell distributions are normalised it should be fine. I can't recall if SCT counts were non-negative though, I assume yes, and their residuals are the mean-normalised ones?

Either way, comparable cell distributions and non-negative counts would work with liana :)

Hope this helps.
