### ISSUE TITLE
LR_means, meaning? 

### ISSUE THREAD

**Issue by soniyalama** [saezlab/liana-py#107]
Hi, and thanks for your tool. 

As exploring your tool, I came upon this LR_means, which I assume is the mean of the ligand and receptor means. But what can you derive from this exactly? In the documentation you talk about the magnitude of the interaction, but could you elaborate on that? Also the cellphone_pvals which are a measure of the specificity of interaction. This was 0 in the adata.uns['cpdb_res'].head() , but when making the dot plot, we see values from 0 to 12. I assume that in the dot plot it's the log p-value? and the higher this value, the more specific this interaction is. What does this specificity imply exactly? 

Kind regards, 
and once again thanks for your quick replies!

**Comment by dbdimitrov** [comment]
Hi @soniyalama,
>  I came upon this LR_means, which I assume is the mean of the ligand and receptor means
> What does this specificity imply exactly?

Correct. It's just a measure of magnitude - i.e. how highly expressed are the two components, as opposed to specificity, or how highly specific is this interaction to a particular pair of cell types.

> This was 0 in the adata.uns['cpdb_res'].head() , but when making the dot plot, we see values from 0 to 12. I assume that in the dot plot it's the log p-value? and the higher this value, the more specific this interaction is.

Correct :)

Hope this helps!

**Comment by dbdimitrov** [comment]
Specificity and Magnitude is in reality just nomenclature to distinguish types of scores in each method, but in reality, they are also correlated - you expect interactions that are specific also to have a high magnitude (in a specific cell pair)
