### ISSUE TITLE
Hypothesis-testing for comparisons between conditions

### ISSUE THREAD

**Issue by grst** [saezlab/liana-py#11]
Hi @dbdimitrov, 

this is to follow up our discussion on methods for differential cell2cell communication in https://github.com/theislab/single-cell-best-practices/pull/140. 

In your NatComm paper and the CCC book chapter, you seem to focus mostly on methods for inferring steady-state cell2cell interactions. However, recently, I tend to encounter more datasets where I actually want to compare cell2cell communication between conditions. 
For instance, in our [lung cancer atlas paper](https://www.cell.com/cancer-cell/fulltext/S1535-6108(22)00499-8), we performed comparisons between the LUAD and LUSC subtypes, or different patient subgroups, driven by the question "how could a certain cell-type shape the tumor microenvironment by expressing certain cell surface ligands?". 

I am currently aware of the following methods to compare between conditions: 

1. [cellphonedb v3](https://github.com/ventolab/CellphoneDB#new-in-cellphonedb-v3). Essentially, the differential expression of ligands and receptors is computed with a DE method of the user's choice. 
2. [differential niechenet](https://github.com/saeyslab/nichenetr/blob/master/vignettes/differential_nichenet.md). Again, this is based on a custom list of differentially expressed genes
3. [iTALK](https://www.biorxiv.org/content/10.1101/507871v1.full) also seems to be based on differential gene expression which can be computed either between cell-types or between conditions. 

All these approaches suffer from the same pseudoreplication-bias problem as single-cell DE in general, so one would need to either use pseudo-bulk or LME models to avoid inflated p-values. 

In the atlas (and also for other projects), so far I have been using DESeq2 on Pseudobulk and a custom [Python reimplementation](https://github.com/icbi-lab/nmp-liver/blob/main/lib/scanpy_helper/scanpy_helpers/cell2cell.py) of the cellphonedb v3 algorithm (https://github.com/icbi-lab/nmp-liver/blob/main/lib/scanpy_helper/scanpy_helpers/cell2cell.py) combined with a list of ligands and receptors from omnipath. I ended up with the following visualization, which shows differentially expressed ligands between conditions at the top, and other cells that express the corresponding receptors (i.e. might be impacted by those changes) at the bottom: 

![image](https://user-images.githubusercontent.com/7051479/218037066-1bafd6ed-20fb-4401-94a7-cabcb9430735.png)

Do you have any other suggestions/recommendations how to best compare cell-cell interactions between conditions? And do you plan to implement any of these methods in liana-py? 

CC @zethson @abyssum

**Comment by earmingol** [comment]
We've been working on integrating LIANA and [Tensor-cell2cell](https://www.nature.com/articles/s41467-022-31369-2) to do so! @dbdimitrov made this [quick start tutorial](https://liana-py.readthedocs.io/en/latest/notebooks/liana_c2c.html), but soon we will release more detailed tutorials and what kind of analysis to do with this, especially comparing multiple samples simultaneously.

**Comment by dbdimitrov** [comment]
PS. The CPDBv3 approach should already be applicable also with liana, just a matter of adding one filter step, following pseudobulk DE and a run of CPDB. One could also request additional `supp_columns` per ligand & receptor - such as log2FC, etc.

**Comment by grst** [comment]
Thanks for sharing your thoughts! I will check out cpdb via liana next time. TC2C also looks interesting, but I think I was more after the "differential communication testing" with pre-defined hypotheses.

**Comment by dbdimitrov** [comment]
@grst, we can leave the issue open and I can notify once pre-defined hypothesis testing is in liana :)

**Comment by earmingol** [comment]
If this helps, [scDiffCom](https://www.biorxiv.org/content/10.1101/2021.08.13.456238v1.full) performs differential analysis at the level of communication scores instead of gene expression.

**Comment by dbdimitrov** [comment]
Hey @grst,

This took longer than anticipated, but I have now added a utility function that does something very much in liana with your suggestion/implementation. I also implemented a tileplot similar to the one you show.

A tutorial is available here and feedback/contributions are more than welcome:
https://liana-py.readthedocs.io/en/latest/notebooks/targeted.html

**Comment by dbdimitrov** [comment]
I will close it now, as it believe it's addressed. Feel free to open another issue :)
