### ISSUE TITLE
Volcano plots for differentially expressed signaling pairs 

### ISSUE THREAD

**Issue by Zach-Sten** [saezlab/liana-py#113]
I've been testing out this package and love it! I think a worthwhile investment would be more plotting functions for dendrograms and volcano plots to visualize the upregulated/downregulated signaling events happening across various groups. I've tried playing around with some plotting functions for the bivariate and cellchat results but am wondering if anyone has more robust functions or if there are plans to include some in the next update. 

Thanks!

**Comment by dbdimitrov** [comment]
Hi @Zach-Sten,

Thanks for using LIANA+ and for the positive feedback. I realize we need to extend the plotting functions, and I will do my best to address at least some of the missing plotting options in the next couple of updates.

In the long run, there are also plans to have others dedicated to the extensions of LIANA+ plotting, besides myself. So, I assume at in the future we will have a very comprehensive set of plotting options.

See related issues:
https://github.com/saezlab/liana-py/issues/83
https://github.com/saezlab/liana-py/issues/85

**Comment by dbdimitrov** [comment]
Re volcano plot:
you can check the volcano plot from decoupler in the meantime:
https://decoupler-py.readthedocs.io/en/latest/notebooks/pseudobulk.html#Contrast-between-conditions

I can also include it as an option in the liana+ tutorial
