### ISSUE TITLE
GeneA_GeneB gene expression level error

### ISSUE THREAD

**Issue by alecdavi** [saezlab/liana-py#115]
Hello,

Thank you really much for this package, it is extremely useful and pleasant to use.
I seem to be experiencing an issue when running `li.mt.rankaggregate` on a single cell sample. Both `Gene_A` and `Gene-B` are not expressed in a specific cell type, but I get strong scores for the LR pair `Gene_C -> Gene_A_Gene_B`. I am not sure where the `Gene_A_Gene_B` expression comes from and what causes this. Maybe you would have an idea ?

**Comment by dbdimitrov** [comment]
Hi @alecdavi,

Is it possible to share a subset of your data? Or at least the code that you're running?

Thanks!

Daniel

**Comment by dbdimitrov** [comment]
PS. I assume you might be using the `.raw` of your data, instead of the X
