### ISSUE TITLE
Import Error: Cannot Import name RandomForestModel

### ISSUE THREAD

**Issue by poloarol** [saezlab/liana-py#116]
Hello,

I have been following the Misty tutorial, and came across this bug:

This is the version of liana-py installed:

`pip install liana[full]`

```
from liana.method.sp import RandomForestModel, LinearModel, RobustLinearModel

ImportError: cannot import name 'RandomForestModel' from 'liana.method.sp'
```

Please any help or directions will be appreciated.

Best,
poloarol

**Comment by dbdimitrov** [comment]
Hi @poloarol, is it possible that you're not using the latest liana version - i.e. 1.2.0?

please run:
`pip install liana --upgrade`, if this doesn't work then there might be an issue.

**Comment by poloarol** [comment]
Hello!

Thanks re-installation worked.

**Comment by dbdimitrov** [comment]
Great. Feel free to open other issues if questions arise :))
