### ISSUE TITLE
Issue with orthologue conversion

### ISSUE THREAD

**Issue by chrika2** [saezlab/liana-py#122]
Hi,

I encounter an issue when i try to convert the genes to from human to zebrafish orthologues with HCOP within LIANA in a jupyter notebook. Error mentions: AttributeError: module 'liana.resource' has no attribute 'get_hcop_orthologs'. 

Any suggestions what might be the problem?

**Comment by dbdimitrov** [comment]
Hi @chrika2,

I would assume that you are likely running an older version of liana.
Please run `pip install liana --upgrade` and let me know if this solves your issue.

Daniel

**Comment by chrika2** [comment]
Great that did the trick i missed the update,thank you very much!

Christos
