### ISSUE TITLE
Does LIANA+ support Visium HD data? 

### ISSUE THREAD

**Issue by Rafael-Silva-Oliveira** [saezlab/liana-py#131]
Hello!

I'd like to test LIANA+ with Visium HD data (which can have more than 500k cells/bins/spots). With this being said, I'd like to know if the features are optimized for such high resolution data or if you guys have any other suggestions on how to do LR/CCI analysis for single cell spatial transcriptomics data?

Thank you!

**Comment by dbdimitrov** [comment]
Hi @Rafael-Silva-Oliveira,

I have not tried running it on Visium HD yet, but most methods run in seconds on 100k cells/spot dataset on my outdated laptop (16GB RAM and CPU from 2019). Exceptions of this would be CellChat's adaptation, or using the local bivariate scores with permutations (score calculation should be fast there, but repeating it 1,000 times would take x1000).  

![image](https://github.com/user-attachments/assets/ba220850-01e3-4d73-805f-087079854e4c)
_Efficiency benchmark of A) dissociated methods and B) spatially-weighted local metrics implemented in LIANA+. Time in log2 of seconds and peak total RAM (memory) usage are shown over a number of simulated datasets with observations (cells) ranging from 1000 to 100,000 (1k to 100k). Note that this is total RAM - i.e. my full Python session usage (not just the LIANA+ run)._

Also, using MISTy with sklearn's models might be a bit slow with 500k observations - but then one might pass a GPU-accelerated version instead.

We also plan to fully GPU accelerate all methods in LIANA+ in the future.

**Comment by Rafael-Silva-Oliveira** [comment]
> Hi @Rafael-Silva-Oliveira,
> 
> I have not tried running it on Visium HD yet, but most methods run in seconds on 100k cells/spot dataset on my outdated laptop (16GB RAM and CPU from 2019). Exceptions of this would be CellChat's adaptation, or using the local bivariate scores with permutations (score calculation should be fast there, but repeating it 1,000 times would take x1000).
> 
> ![image](https://private-user-images.githubusercontent.com/50865230/355720136-ba220850-01e3-4d73-805f-087079854e4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTY4MTAsIm5iZiI6MTcyMzAxNjUxMCwicGF0aCI6Ii81MDg2NTIzMC8zNTU3MjAxMzYtYmEyMjA4NTAtMDFlMy00ZDczLTgwNWYtMDg3MDc5ODU0ZTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA3NDE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyOWYwMWNhOTk3OGMxYjA1NGE4YWEyNDU3OTQ0OTg3YzliMzU0M2E1ZDRmMzU0NWQ1YzdhYjQxNWEwMzhmYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4iADqDugQkhl8sf_mYVFOP5iaHL3pNdfeKsTOxYPRfc) _Efficiency benchmark of A) dissociated methods and B) spatially-weighted local metrics implemented in LIANA+. Time in log2 of seconds and peak total RAM (memory) usage are shown over a number of simulated datasets with observations (cells) ranging from 1000 to 100,000 (1k to 100k). Note that this is total RAM - i.e. my full Python session usage (not just the LIANA+ run)._
> 
> Also, using MISTy with sklearn's models might be a bit slow with 500k observations - but then one might pass a GPU-accelerated version instead.
> 
> We also plan to fully GPU accelerate all methods in LIANA+ in the future and likely calculate the matrices in batches to further reduce RAM usage.

Thank you very much for the swift reply! Great to hear

 I'll be giving it a go, much appreciated and great work with the package - Looking forward to see the improvements down the line too!

**Comment by Rafael-Silva-Oliveira** [comment]
I've reopened because it seems that even just calcualting spatial neighbors it gives memory errors

``` li.ut.spatial_neighbors(adata, bandwidth=50, cutoff=0.1, kernel='gaussian', set_diag=False)```

```MemoryError: Unable to allocate 201. GiB for an array with shape (519722, 51973) and data type float64```

I'm using the 10X Visium HD lung dataset from 10X website, 8 micron. Then, I'm preprocessing with Bin2Cell to aggregate bins into actual cells which gives me around 520k cells (from the original 650 or so thousand bins)

So I'm assuming it isn't quite appropriate for this use case? :)

Thank you

**Comment by dbdimitrov** [comment]
Hi @Rafael-Silva-Oliveira,

I'm 99% sure that this is because of the `max_neighbours` which by default would calculate distances between 1/10 of the observations (which is 50,000 in the visium HD case). If you change this to e.g. 20, then it should work.

Please let me know if this works. If it does, I should probably change the default param to some integer, e.g. 50 instead of a proportion of all obs.

**Comment by Rafael-Silva-Oliveira** [comment]
> Hi @Rafael-Silva-Oliveira,
> 
> I'm 99% sure that this is because of the `max_neighbours` which by default would calculate distances between 1/10 of the observations (which is 50,000^2 of non-sparse distances in the visium HD case). If you change this to e.g. 10/20, then it should work.
> 
> Please let me know if this works. If it does, I should probably change the default param to some integer instead of a proportion of all obs.
> 
> You could also use the Squidpy connectivities, if this does not work :)

Nice, that seems to work, thank you :)

I am now getting this error when doing this:

`li.pl.connectivity(adata=adata, idx=0, size=1.3, figure_size=(6, 5))`

If I replace this line of code:

```
coordinates = pd.DataFrame(adata.obsm["spatial"],index=adata.obs_names,columns=['x', 'y']).copy()
coordinates['connectivity'] = adata.obsp["spatial_connectivities"][:, 0].A

```

with 

```
coordinates['connectivity'] = adata.obsp["spatial_connectivities"][:, 0].toarray()


```

It works

My coordinates look like this:

![image](https://github.com/user-attachments/assets/8a2bbca5-3e56-4f6f-b851-d8e6e094d4ef)

And my adata.X is

```<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 90110045 stored elements and shape (519722, 17038)>```

**Comment by dbdimitrov** [comment]
Hi @Rafael-Silva-Oliveira,

Can you convert the matrix to [csr_sparse](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html) instead of array?

**Comment by Rafael-Silva-Oliveira** [comment]
> Hi @Rafael-Silva-Oliveira,
> 
> ~Can you convert the matrix view to [csr_sparse](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html) instead of array?~
> 
> PS. I realized that I'm now converting to array internally, it used to be only for small matrices - but yeah we don't want that. I will try to resolve for the next update. I'll also try it on Visium HD myself.
> 
> I will keep you posted.

Thank you very much for the help! Looking forward for the updated :) For reference, I'm using the 10X Visium HD lung dataset 8 micron resolution processed after Bin2Cell, but for testing purposes the normal 8 micron resolution should do just fine!

I'm downloading the adata file to my local env, do let me know if you'd like me to upload it so you can download it (and then just load with sc.read_h5ad)

Thank you!

**Comment by dbdimitrov** [comment]
Hi @Rafael-Silva-Oliveira,

Yeah, please if you could upload an anndata somewhere, that would save me a lot of time. Thanks.

**Comment by Rafael-Silva-Oliveira** [comment]
> Hi @Rafael-Silva-Oliveira,
> 
> Yeah, please if you could upload an anndata somewhere, that would save me a lot of time. Thanks.

Let me know if you're able to download from this provider: https://easyupload.io/wjst7v

This is the 8 micron dataset which I then processed with Bin2Cell to retrieve the actual cell coordinates (in Visium HD we have the inverse problem - one single cell can span across multiple bins) and I predited the cell types (adata.obs["cell_type"]) using CellTypist

**Comment by Rafael-Silva-Oliveira** [comment]
I also noticed that printing the result of `xy_stats['interaction'] = xy_stats[self.x_name] + xy_sep + xy_stats[self.y_name]` results in:

`Series([], Name: interaction, dtype: object)`

Which is empty

What should this series be exactly? 

Thank you

**Comment by dbdimitrov** [comment]
Hi @Rafael-Silva-Oliveira, is your `nz_prop` filter too high?

**Comment by Rafael-Silva-Oliveira** [comment]
> Btw, if you have a cell type assigned to each bin, you could use the 'standard' ligand-receptor methods from liana, after you e.g. filter to cell types that are known to interact (via the `groupby_pairs` parameter https://liana-py.readthedocs.io/en/latest/api/liana.method.rank_aggregate.__call__.html). For example, you could check the NES of cell type pairs using squidpy and then subset the interactions that liana returns to the significantly associated cell types.

Hi, thank you for the swift replies!

Would that suggestion look something like this? 

```
import squidpy as sq

sq.gr.spatial_neighbors(adata, key_added="spatial_neighbors")
sq.gr.interaction_matrix(adata, cluster_key="cell_type", key_added="interactions")

# Compute NES
sq.gr.nhood_enrichment(adata, cluster_key="cell_type", n_perms=1000)

nes_results = adata.uns['nhood_enrichment']['zscore']

liana_results = li.rank_aggregate(adata, groupby="cell_type")

significant_cell_types = nes_results[nes_results['zscore'] > 1.96].index

filtered_liana_results = liana_results[liana_results['source'].isin(significant_cell_types) & liana_results['target'].isin(significant_cell_types)]

```

Or am I misinterpreting? 

Thanks!

**Comment by Rafael-Silva-Oliveira** [comment]
> Hi @Rafael-Silva-Oliveira, is your `nz_prop` filter too high?

I'm testing with the default values from the tutorial, I'll test something lower

**Comment by dbdimitrov** [comment]
Yeah, passing the significant source, target (groupby_pairs) dataframe from squidpy to liana would essentially do the same filter, but it would be faster since it won't calculate any interactions for cell type pairs that are not provided :)

Ughh yeah sorry, I meant as long as you have one cell type per observation - i.e. it's labels not proportions.

**Comment by Rafael-Silva-Oliveira** [comment]
> Yeah, passing the significant source, target (groupby_pairs) dataframe from squidpy to liana would essentially do the same filter, but it would be faster since it won't calculate any interactions for cell type pairs that are not provided :)
> 
> Ughh yeah sorry, I meant as long as you have one cell type per observation - i.e. it's labels/one-hot and not proportions.

Nice, I will give it a shot!

Do you know by any chance if that would involve running this command?

```
res = sq.gr.ligrec(adata=adata,     
    n_perms=100,
    cluster_key="leiden_clusters",
    copy=True,
    use_raw=False,
    transmitter_params={"categories": "ligand"},
    receiver_params={"categories": "receptor"},
)

```

Because if that's the case (to get the dataframe of source, target to put through the groupby_pairs), then I don't think I'll be able to as it also gives me memory errors - https://github.com/scverse/squidpy/issues/819

Running the liana aggregate also gives me this:

liana_results = li.mt.rank_aggregate(adata, groupby="cell_type")


```

 raise ValueError(msg + f" [{x_missing}] missing from {superset_name}")
ValueError: Please check if appropriate organism/ID type was provided! Allowed proportion (0.98) of missing resource elements exceeded (0.99). Too few features from the resource were found in the data. [A1BG, A2M, AANAT, ABCA1, ACE, ACKR1, ACKR2, ACKR3, ACKR4, ACTR2, ACVR1, ACVR1B, ACVR1C, ACVR2A, ACVR2B, ACVRL1, ADA, ADAM10, ADAM11, ADAM12, ADAM15, ADAM17, ADAM2, ADAM22, ADAM23, ADAM28, ADAM29, ADAM7, ADAM9, ADAMTS3, ADCY1, ADCY7, ADCY8, ADCY9, ADCYAP1...

``` 

But if I check my adata.var_names, I can see for example that the gene "ACVR1" is in index 2411, while A1BG is not present in my adata

My adata.var_names are also all upper cased - I'm sure I'm missing something very basic, but can't quite see what 😮‍💨

**Comment by dbdimitrov** [comment]
Hi @Rafael-Silva-Oliveira,

The first one is essentially running CellPhoneDB via Squidpy, instead of liana.

For the liana error, it's either that your `expr_prop` is too high or indeed it's a different organism? If it's mouse data, you could pass `resource_name='mouseconsensus'`, instead of uppercasing.

**Comment by Rafael-Silva-Oliveira** [comment]
> Hi @Rafael-Silva-Oliveira,
> 
> The first one is essentially running CellPhoneDB via Squidpy, instead of liana.
> 
> For the liana error, it's either that your `expr_prop` is too high or indeed it's a different organism? If it's mouse data, you could pass `resource_name='mouseconsensus'`, instead of uppercasing.

I had to do adata.raw = adata.copy() since my adata had upper case genes, but the raw didn't :)

**Comment by dbdimitrov** [comment]
You can use `use_raw=False` 😉

**Comment by Rafael-Silva-Oliveira** [comment]
> You can use `use_raw=False` 😉

Yep, as expected, something super simple that I didn't notice ahah Thank you again!

**Comment by Rafael-Silva-Oliveira** [comment]
> running CellPhoneDB via Squidpy

Also regarding the running CellPhoneDB via squidpy, I'm afraid I am unable to run it even on a server as it just simply crashes, so I'll be waiting for the new implementation on LIANA :)

**Comment by dbdimitrov** [comment]
@Rafael-Silva-Oliveira so running li.mt.cellphonedb also did not work with liana in the end? Just so that I know what I should try with the data.

**Comment by Rafael-Silva-Oliveira** [comment]
> @Rafael-Silva-Oliveira so running li.mt.cellphonedb also did not work with liana in the end? Just so that I know what I should try with the data.

OK, I retried with cellphonedb and it worked:

```

ligrec_pairs = li.mt.cellphonedb(
    adata,
    groupby="cell_type",
    resource_name="consensus",
    expr_prop=0.1,
    verbose=True,
    use_raw=False,
    key_added="cpdb_res",
)

```
Which gives me this:

```
    ligand ligand_complex  ligand_means  ...       target  lr_means cellphone_pvals
376  ADCYAP1        ADCYAP1      1.571429  ...  Endothelial  0.955073           0.000
225  ADCYAP1        ADCYAP1      1.571429  ...         Club  0.857143           0.000
483      APP            APP      0.364370  ...   Macrophage  0.749124           0.000
494      APP            APP      0.360406  ...   Macrophage  0.747142           0.000
502      APP            APP      0.260780  ...   Macrophage  0.697329           0.000
..       ...            ...           ...  ...          ...       ...             ...
220     NRG1           NRG1      0.142857  ...         Club  0.142857           0.064
226     CALR           CALR      0.142857  ...         Club  0.142857           0.187
178     COPA           COPA      0.138776  ...         Club  0.140816           0.431
276   COL1A1         COL1A1      0.138614  ...         Club  0.140736           0.090
289    NFASC          NFASC      0.120690  ...         Club  0.131773           0.042

```

And allows me to run the aggregate function as such:


```

liana_results = li.mt.rank_aggregate(
    adata,
    groupby="cell_type",
    use_raw=False,
    groupby_pairs=adata.uns["cpdb_res"],
)

```

And I can access this through adata.uns["liana_res"]

```

             source       target ligand_complex  ...   lrscore  specificity_rank  magnitude_rank
254            Club  Endothelial        ADCYAP1  ...  0.978020          0.003170        0.000015
328     Endothelial   Macrophage            APP  ...  0.975126          0.009181        0.000134
566  Neuroendocrine   Macrophage            APP  ...  0.974993          0.009505        0.000238
759            Tuft   Macrophage            APP  ...  0.970730          0.009505        0.001198
91              AEP   Macrophage            APP  ...  0.970252          0.009505        0.001478
..              ...          ...            ...  ...       ...               ...             ...
697          SCLC-P     Ciliated          TIMP1  ...  0.923625          1.000000        1.000000
168           Basal     Ionocyte            APP  ...  0.919585          1.000000        1.000000
668          SCLC-N     Ciliated            APP  ...  0.917972          1.000000        1.000000
119          B cell         Club        ADCYAP1  ...  0.920804          1.000000        1.000000
109          B cell          AE1            APP  ...  0.927069          1.000000        1.000000

```
So this seems to be a nice work around until the bivariate function is updated. Although, this approach only shows the lr_score as a whole, correct? It's missing the bivariate component of the results from ligand and receptor, would that be it?

Thanks again

**Comment by dbdimitrov** [comment]
Hey @Rafael-Silva-Oliveira,

I tested both local bivariate and the Rank Aggregate and both run < 1 min TBH, most of the RAM usage (total RAM in my case ~13GB) comes from simply loading the Visium HD anndata and then when LIANA+ creates a new anndata for the local ligand-receptor scores. 

However, if you want to do permutations /w the local scores that's a bit slower, ~15 min for 100 permutations.

I uploaded a kind of rough notebook with the points we discussed here:
https://colab.research.google.com/drive/1JJi-if2ht4dxS6d9cbNrZzqxizAOjOvr?authuser=2

But yeah, in general, LIANA+ works quite well already with VisiumHD. Though, yeah GPU acceleration would make everything lightning fast :)

**Comment by Rafael-Silva-Oliveira** [comment]
> Hey @Rafael-Silva-Oliveira,
> 
> I tested both local bivariate and the Rank Aggregate and both run < 1 min TBH, most of the RAM usage (total RAM in my case ~13GB) comes from simply loading the Visium HD anndata and then when LIANA+ creates a new anndata for the local ligand-receptor scores.
> 
> However, if you want to do permutations /w the local scores that's a bit slower, ~15 min for 100 permutations.
> 
> I uploaded a kind of rough notebook with the points we discussed here: https://colab.research.google.com/drive/1JJi-if2ht4dxS6d9cbNrZzqxizAOjOvr?authuser=2
> 
> But yeah, in general, LIANA+ works quite well already with VisiumHD. Though, yeah GPU acceleration would make everything lightning fast :)

Thank you very much! I'm trying to access the notebook but I'm getting this: 

```
Notebook loading error
There was an error loading this notebook. Ensure that the file is accessible and try again.
```

That bivariate test, was that with the amended array as well? Or did you manage to run using the current version of Liana? :)

**Comment by dbdimitrov** [comment]
Re: yeah the standard single-cell methods (i.e.g CellPhoneDB, RankAggregate) would only do global. Also, for the groupby pairs, I meant to pass only those that are reported as spatially-associated by some metric. This can be MISTy, Global Morans' R (via liana), or NES from squidpy, etc.

> That bivariate test, was that with the amended array as well? Or did you manage to run using the current version of Liana? :)

The current version. I assume it might be due some operation done just before the bivar scores that transform X into a view?

**Comment by dbdimitrov** [comment]
> There was an error loading this notebook. Ensure that the file is accessible and try again.

Hmm, I can access it in incognito mode and it's shared, so not sure. I can add you as an author if you give me an email.

**Comment by Rafael-Silva-Oliveira** [comment]
> https://colab.research.google.com/drive/1JJi-if2ht4dxS6d9cbNrZzqxizAOjOvr?authuser=2

Incognito fixed it 👍 

Regarding the bivariate test, I'm still getting the `AttributeError: 'SparseCSRView' object has no attribute 'A'`


```

>>> li.mt.bivariate(
...     adata,
...     resource_name="mouseconsensus",  # NOTE: uses HUMAN gene symbols!
...     local_name="cosine",  # Name of the function
...     global_name="morans",  # Name global function
...     n_perms=None,  # Number of permutations to calculate a p-value
...     mask_negatives=False,  # Whether to mask LowLow/NegativeNegative interactions
...     add_categories=False,  # Whether to add local categories to the results
...     nz_prop=0.01,  # Minimum expr. proportion for ligands/receptors and their subunits
...     use_raw=False,
...     verbose=True,
... )
Using `.X`!
79 features of mat are empty, they will be removed.
Using resource `mouseconsensus`.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/work/RO_src/venv/stnav_venv/lib/python3.10/site-packages/liana/method/sp/_bivariate/_spatial_bivariate.py", line 223, in __call__
    local_fun(x_mat=x_mat,
  File "/mnt/work/RO_src/venv/stnav_venv/lib/python3.10/site-packages/liana/method/sp/_bivariate/_local_functions.py", line 39, in __call__
    x_mat = x_mat.A
AttributeError: 'SparseCSRView' object has no attribute 'A'

```

I might try a fresh venv with just LIANA and the dependencies as this might be an issue from different package versions, although I'm not finding any dependency errors in my current venv;

I'll give that a try and I'll let you know how it goes!

**Comment by dbdimitrov** [comment]
@Rafael-Silva-Oliveira TBH I don't understand why your X matrix is a view at that stage - LIANA+ recreates a minimized anndata object internally. 

Can you pass a layer instead, i.e. `layer='normcount_x'`, I don't remember the exact way you called your log-normalized counts. I can't reproduce the error on my side, so it must be a versioning issue?

**Comment by Rafael-Silva-Oliveira** [comment]
> @Rafael-Silva-Oliveira TBH I don't understand why your X matrix is a view at that stage - LIANA+ recreates a new minimized anndata object internally.
> 
> Can you pass a layer instead, i.e. `layer='normcount_x'`, I don't remember the exact way you called your log-normalized counts. I can't reproduce the error on my side, so it must be a versioning issue?

Still the same error passing the layer instead, so I'm assuming it is a versioning issue, but I've reinstalled the packages and created new venvs and still the same error 

Btw what python version are you using for these tests? :)

**Comment by dbdimitrov** [comment]
Might be a scipy issue?

See partial session below:
```
Python 3.8.18 (default, Sep 11 2023, 13:40:15) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> scipy.__version__
'1.10.1'
>>> import liana
>>> liana.__version__
'1.3.0'
>>> 
```

**Comment by Rafael-Silva-Oliveira** [comment]
> Might be a scipy issue?
> 
> See partial session below:
> 
> ```
> Python 3.8.18 (default, Sep 11 2023, 13:40:15) 
> [GCC 11.2.0] :: Anaconda, Inc. on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import scipy
> >>> scipy.__version__
> '1.10.1'
> >>> import liana
> >>> liana.__version__
> '1.3.0'
> >>> 
> ```

Yep, I think we found the issue 


When installing Liana as a fresh installation (no other installations in the venv), it installed scipy==1.4.0. After reinstalling with your version (1.10.1) it now runs fine 👍 

```
lrdata.var.sort_values("morans").tail(10)
              ligand receptor  ligand_means  ...  morans_pvals      mean       std
interaction                                  ...                                  
APP^NCSTN        APP    NCSTN      0.077191  ...          None  0.054743  0.099248
SPP1^CD44       SPP1     CD44      0.022663  ...          None  0.015111  0.084249
CXCL12^CXCR4  CXCL12    CXCR4      0.009967  ...          None  0.017744  0.091871
CD14^ITGB2      CD14    ITGB2      0.019055  ...          None  0.033416  0.127891
APOE^LRP1       APOE     LRP1      0.068173  ...          N
```

**Comment by dbdimitrov** [comment]
Thanks for the help debugging it! I will check if I can reproduce the error with scipy==1.4.0, and I'll make sure to resolve for next version.

**Comment by Rafael-Silva-Oliveira** [comment]
> Thanks for the help debugging it! I will check if I can reproduce the error with scipy==1.4.0, and I'll make sure to resolve for next version.

I was missing a "1" on my previous comment - The actual version where I was getting the error was the latest one (1.14.0) :)

For reference, my python version is 3.10.12

**Comment by dbdimitrov** [comment]
Hi,

This is now up and might be more relevant: https://liana-py.readthedocs.io/en/latest/notebooks/inflow_score.html

Daniel
