### ISSUE TITLE
Support for Calligraphy ?

### ISSUE THREAD

**Issue by divyanshusrivastava** [saezlab/liana-py#134]
Kudos to the amazing tool. 

I was wondering if the team is also planning to incorporate Calligraphy into the list of available methods.
https://www.science.org/doi/10.1126/science.add5327

**Comment by dbdimitrov** [comment]
Hi @divyanshusrivastava,

Currently, there is no plan to add caligraphy. Although, this might change when liana changes its main developer :)

We also welcome contributions, in case this was the direction of your question 😉 

Daniel
