### ISSUE TITLE
AttributeError: module 'corneto.methods.carnival' has no attribute '_extended_carnival_problem'

### ISSUE THREAD

**Issue by gianfilippo** [saezlab/liana-py#142]
Hi,

I am running li.mt.find_causalnet following the tutorial (with my data)
df_res, problem = li.mt.find_causalnet(prior_graph, input_scores, output_scores, node_weights, node_cutoff=0.1, max_penalty=1, min_penalty=0.01, edge_penalty=0.1,verbose=True, max_runs=50, stable_runs=10, solver='gurobi')
 
I get the following output
Total positive/negative scores of the inputs and outputs:
 - (-) input nodes: -7.810769193348582
 - (+) input nodes: 20.494407934579563
 - (-) output nodes: 0
 - (+) output nodes: 56.59489059448242
 - abs total (inputs + outputs): 84.90006772241057
Building CORNETO problem...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.conda/envs/Liana+/lib/python3.11/site-packages/liana/method/fun/_causalnet.py", line 193, in find_causalnet
    P, G = cn.methods.carnival._extended_carnival_problem(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'corneto.methods.carnival' has no attribute '_extended_carnival_problem'

can you please help ?

cn.info()
Installed version: v1.0.0.dev0 (up to date)
Available backends: CVXPY v1.5.3, PICOS v2.4.17
Default backend (corneto.opt): CVXPY
Installed solvers: CBC, CLARABEL, CVXOPT, ECOS, ECOS_BB, GLPK, GLPK_MI, GUROBI, OSQP, SCIPY, SCS
Graphviz version: v0.20.3
Repository: https://github.com/saezlab/corneto

**Comment by dbdimitrov** [comment]
Hi @gianfilippo 

It seems like this is a corneto version issue, can you please try again after running:

`pip install corneto==0.9.1-alpha.5`

**Comment by pablormier** [comment]
Duplicated also here: https://github.com/saezlab/corneto/issues/12

**Comment by gianfilippo** [comment]
thanks. It works now!

I think I have a similar issue with Seaborn when running c2c.plotting.context_boxplot
I get AttributeError: module 'seaborn.categorical' has no attribute '_BoxPlotter'

I reinstaled with seaborn==0.11, but it required to reinstall a previous version of scanpy.
Also, another error related to matplotlib was generated by cell2cell

It seems that to run your tutorials one need to install in the following way, to avoid reinstall and errors
python -m pip install liana cell2cell decoupler>=0.1.4 omnipath seaborn==0.11 mofax muon omnipath marsilea matplotlib==3.7.3

**Comment by dbdimitrov** [comment]
Yeah all the plotting libraries we all use are really making things complicated.

You could also install liana with poetry then it would use the environment that I use for liana.

**Comment by dbdimitrov** [comment]
Thanks for the patience with the plotting. There is a grant that will start soon during which there will be a person who will look into CCC plotting. So, hopefully these issues will be resolved.

**Comment by gianfilippo** [comment]
I think it is ok now. i will keep poetry in mind, just in case.
In any case, thanks your help and for developing this package. It is really great!

**Comment by dbdimitrov** [comment]
No worries. Thanks for using it.

I'll close the issue. Feel free to open new ones.
