### ISSUE TITLE
why the output dont include the cellchat part?

### ISSUE THREAD

**Issue by LJZYaaa** [saezlab/liana-py#145]
after i run the command li.mt.rank_aggregate.by_sample, i find that the result don't have the part of cellchat what is called 'lr_probs' in the tutorail, why ?
![image](https://github.com/user-attachments/assets/52b8afa2-cab8-44cc-93c6-1292b820649f)

**Comment by dbdimitrov** [comment]
Hi @LJZYaaa,

You would need to add CellChat as a method to RankAggregate in order to get it's output:
See here:
https://liana-py.readthedocs.io/en/latest/notebooks/basic_usage.html#Customizing-LIANA's-rank-aggregate

Daniel

**Comment by LJZYaaa** [comment]
Hi, gald to receive your reply ! But when i try to run the stand standard code in tutorial as below, it report an error :)
![image](https://github.com/user-attachments/assets/5a01c774-5c29-419f-9caa-ed550df9e236)
Do you have any idea about it ?

**Comment by dbdimitrov** [comment]
Hi @LJZYaaa

Yes, you must import those objects from liana - as done in a few lines above in the same tutorial.

Daniel
