### ISSUE TITLE
module 'seaborn.categorical' has no attribute '_BoxPlotter'

### ISSUE THREAD

**Issue by LJZYaaa** [saezlab/liana-py#148]
Hi, recently i am trying to follow the tutorial of "Intercellular Context Factorization with Tensor-Cell2cell" ,but when i run the command as below,
![image](https://github.com/user-attachments/assets/db3f10b1-ed18-4c70-8f49-d37115f1e98b)
it report that :
![image](https://github.com/user-attachments/assets/52c6c87b-6cee-4235-844d-9291a69a5aef)
Can you ples give me some advice for solving this problem?
Thank you in advance!^^

**Comment by dbdimitrov** [comment]
Hi,

Sorry for the delayed response. It appears Erick has already replied:
https://github.com/earmingol/cell2cell/issues/63

But yeah it's most definitely a versioning issue.
