### ISSUE TITLE
Interpretation of negative PROGENY scores and context loadings

### ISSUE THREAD

**Issue by wgao688** [saezlab/liana-py#151]
Hi there,

Thank you for creating this very neat package. I had a question concerning the interpretation of the loadings and the footprint analysis. 

For example, in the tutorial shown (see below), you show how Factor 5 is significantly higher in the severe COVID case. Then, using the footprint enrichment analysis, you identify a positive activity score for JAK-STAT. The interpretation then is that JAK-STAT signaling is higher in the severe COVID cases, and then we can identify individual receptor-ligand interactions that are important for this. 

My question concerns the _**negative**_ enrichment scores. Would it be fair to say that in the example below, PI3K signaling is significantly down in the severe COVID cases, or that it is significantly higher in the controls? And that something like hypoxia or TGF-beta, whose loading scores are close to 0, show little difference across the conditions? 

![image](https://github.com/user-attachments/assets/a45f9b26-f79f-40a6-8fd7-923e10db3deb)
![image](https://github.com/user-attachments/assets/1421a6b8-9735-49c3-ad47-59315d8a50b2)

Thanks!

**Comment by dbdimitrov** [comment]
Hi @wgao688, indeed being down-regulated in COVID cases would be the correct interpretation. Though, I must mention that an activities correspond to t-values here, so it's close to the threshold of 'significance'. 

I'd also recommend checking the interaction loadings that are associated with this pathway as it could be that few interaction are leading to this enrichment, see https://ccc-protocols.readthedocs.io/en/latest/notebooks/ccc_python/06-Functional-Footprinting.html#Footprint-Enrichment

Hope this helps.
Daniel
