### ISSUE TITLE
Use of .obs features in bivariate statistics

### ISSUE THREAD

**Issue by peterpdu** [saezlab/liana-py#152]
Hi,

Is there any plan to add the option to use features in .obs for li.mt.bivariate? For example, if I calculate two gene set scores and want to check their spatial relationship?

**Comment by dbdimitrov** [comment]
hope this help!

**Comment by peterpdu** [comment]
Hi @dbdimitrov, thanks that works!

Related to this, I wanted to ask if the built-in normalization strategies are suitable for non-expression data, such as features with negative values or one-hot encoded values. And if they are not, if there is a way to disable the default normalization.

**Comment by dbdimitrov** [comment]
Hi normalization is assumed to be done before liana, so there is no internal normalization.

See [here](https://liana-py.readthedocs.io/en/latest/notebooks/bivariate.html#Estimate-Cosine-Similarity), I pass the normalization function fo each modality. Here, being simply z-transforming, one could use any alternative functions, e.g. 
- https://liana-py.readthedocs.io/en/latest/api/liana.utils.neg_to_zero.html#liana.utils.neg_to_zero
- https://liana-py.readthedocs.io/en/latest/api/liana.utils.zi_minmax.html#liana.utils.zi_minmax

Hope this helps.

**Comment by peterpdu** [comment]
great, thanks for the references as well!
