### ISSUE TITLE
Cell2cell or MOFA taking into account the spatial information

### ISSUE THREAD

**Issue by kousaa** [saezlab/liana-py#153]
**Is your feature request related to a problem? Please describe.**
Hi Liana team, and thank you for building such a beautiful tool. I am currently dealing with multiple Xenium slides, of multiple samples and conditions; I have found that running the cell2cell and MOFA models exrtemely helpful for interpretation, but I can't work out a way to include in the model the spatial information I have. 
**Describe the solution you'd like**
I would like that the cell type interactions/pathway predictions are somehow weighted/influenced by the proximity of the cells/cell types to each other. It may even be possible to somehow combine the Misty calculated weights with your cell2cell or MOFA models but I have not managed to work out the way.

Would you have a recommendation? I am more than happy to work with your team to help and build this as extra feature/tutorial as it would massively helpful for my data exploration.

Thank you!
Anastasia

**Comment by dbdimitrov** [comment]
Hi @kousaa,

I believe the most straightforward way to apply mofa and tensor on Xenium would be to restrict your results to cell-type and ligand-receptor pairs which are co-localized. The former is also a strategy used by CellPhoneDBv3 and CellChatv2, and what I combined both for the analyses in the liana-py manuscript.

Say you identify some relationships between cell types and ligand/receptors (e.g. according to misty interaction importances or global bivariate scores), then you could run any method from liana, passing `groupby_pairs` (or a dataframe of source-target for cell types which are spatially-associated), and the liana resource (ligand-receptor) dataframe, subsetted to only ligand-receptors which are also spatially-associated.

From there on, you can proceed with MOFA/Tensor as done in the tutorials.

Let me know if I can clarify further :)

Daniel

**Comment by kousaa** [comment]
Thank you so much @dbdimitrov for the very elaborate response! I will give it a go and let you know if I get stuck anywhere. :-)
