### ISSUE TITLE
How to obtain the global (and local) score vectors used to plot the interactions for each spatial location on the slide?

### ISSUE THREAD

**Issue by gauravgadhvi** [saezlab/liana-py#154]
Hi, 
Thank you for your great tool!

I am trying to evaluate LIANA's bivariate metrics using the following code on a 10x Visium HD dataset : 
```

li.mt.bivariate(A1_16um_adata,
                resource=cellphnDB_df_filt,
                local_name = 'cosine',
                global_name = 'morans',
                n_perms= 50,
                mask_negatives=False,
                add_categories=True,
                nz_prop=0.001,
                use_raw=False,
                verbose =True)

## Extract LR data results
A1_16um_LRdata = A1_16um_adata.obsm['local_scores']
 
```
I lowered the nz_prop value to detect subtle interactions. I used a custom dataframe (ligand, receptor) as the resource for evaluating the interactions as we are interested in only a handful of L-R interactions for metrics evaluation.
Upon extracting the local scores, I am getting a result dataframe with values for morans which I believe is the Moran's R? If that's the case, is this the global metric or local metric (calculated using cosine)? 

Also, how do I extract the local and global metrics for each spatial coordinate (based on which the interaction is plotted)? Is there a way to extract the vector or dataframe for each spatial barcode with the global/local metric which is used for coloring the spots using **sc.pl.spatial()** in the example (https://liana-py.readthedocs.io/en/latest/notebooks/bivariate.html)?

Thank you, I appreciate your help!

**Comment by dbdimitrov** [comment]
Hi @gauravgadhvi,

Thanks for using liana :)

To clarify, local scores are per observation (cell/spot), while the global statistics are a single value for each ligand-receptor (lr) interaction.

The local scores would be saved in `.X` (a matrix of obs x lr) in the anndata object returned by liana, while the global statistics are in `.var` (a dataframe with stats for each lr).

Let me know if this answers your questions.

Daniel
