### ISSUE TITLE
Automatic sorting of LR results

### ISSUE THREAD

**Issue by PauBadiaM** [saezlab/liana-py#22]
Right now LR results are not sorted by default, this can cause problems if users are not aware of it and just take the top N rows of the returned dataframe without checking the stats values.

A solution could be to sort the obtained results by the default stat of each method, be it magnitude or specificity score.

**Comment by dbdimitrov** [comment]
Thanks. I will change it in the next update, so that all methods are ranked by magnitude scores if available.
