### ISSUE TITLE
comparison across conditions

### ISSUE THREAD

**Issue by Wulin-Tan** [saezlab/liana-py#5]
Hi, liana team
in liana R version, there is 'LIANA across Conditions with cell2cell-Tensor'.
Is it possible to add this feature (or even other features) to liana-py?
Since sc dataset can be run more efficiently in python and liana is such a useful tool.
Thank you.

**Comment by dbdimitrov** [comment]
> Is it possible to add this feature (or even other features) to liana-py?

liana-py will be the development focus from now on, so all meaningful features from R will be also implemented here, along with certain extensions.

Daniel

**Comment by hmbaghdassarian** [comment]
> In the meantime, perhaps @earmingol or @hmbaghdassarian can provide a temporary function to convert liana's results into the format needed by tensor?

@earmingol has included a function in cell2cell to do that ([tensor.external_scores.dataframes_to_tensor](https://earmingol.github.io/cell2cell/documentation/#cell2cell.tensor.external_scores)). You can run LIANA on each sample/context separately, put the outputs in a dictionary, then use the dataframes_to_tensor function to create the tensor.

**Comment by earmingol** [comment]
> > In the meantime, perhaps @earmingol or @hmbaghdassarian can provide a temporary function to convert liana's results into the format needed by tensor?
> 
> @earmingol has included a function in cell2cell to do that ([tensor.external_scores.dataframes_to_tensor](https://earmingol.github.io/cell2cell/documentation/#cell2cell.tensor.external_scores)). You can run LIANA on each sample/context separately, put the outputs in a dictionary, then use the dataframes_to_tensor function to create the tensor.

To add more about this, once you build the tensor using the function that @hmbaghdassarian mentioned, you can easiy run Tensor-cell2cell using the function ```run_tensor_cell2cell_pipeline``` [in this documentation](https://earmingol.github.io/cell2cell/documentation/#cell2cell.analysis.tensor_pipelines)

**Comment by dbdimitrov** [comment]
Hi @Wulin-Tan,

With developments on both sides (i.e. with @earmingol and @hmbaghdassarian) we have now made a brief tutorial how to combine liana and tensor-cell2cell:
https://liana-py.readthedocs.io/en/latest/notebooks/liana_c2c.html

I'm closing the issue, but feel free to open others if you encounter issues.
