### ISSUE TITLE
Missing Resources

### ISSUE THREAD

**Issue by pallikheni** [saezlab/liana-py#53]
I have been trying to run liana and I get this error. I have checked var_names and they are in the human gene symbol format. Furthermore, I have manually checked the var_names that are printed in the error message as "missing from var_names" are actually present in the adata. I was hoping to get some further guidance on how I could resolve this. Thank you. 

li.mt.rank_aggregate(a_immune, groupby='cell_type', expr_prop=0.1, verbose=True)

ValueError: Please check if appropriate organism/ID type was provided! Allowed proportion (0.98) of missing resource elements exceeded (1.00). Too few features from the resource were found in the data. [A1BG, A2M, AANAT, ABCA1, ACE, ACKR1, ACKR2, ACKR3, ACKR4, ACTR2, ACVR1, ACVR1B, ACVR1C, ACVR2A, ACVR2B, ACVRL1, ADA, ADAM10, ADAM11, ADAM12, ADAM15, ADAM17, ADAM2, ADAM22, ADAM23, ADAM28, ADAM29, ADAM7, ADAM9, ADAMTS3, ADCY1, ADCY7, ADCY8, ADCY9, ADCYAP1, ADCYAP1R1, ADGRA2, ADGRB1, ADGRE2, ADGRE5, ADGRG1, ...  WNT16, WNT2, WNT2B, WNT3, WNT3A, WNT4, WNT5A, WNT5B, WNT6, WNT7A, WNT7B, WNT8A, WNT8B, WNT9A, WNT9B, XCL1, XCL2, XCR1, YBX1, ZG16B, ZNRF3, ZP3] missing from var_names

**Comment by dbdimitrov** [comment]
Hi @pallikheni,

If the symbols indeed match, then this might indeed be a bug.
Can you share a subset of your AnnData object so that I can debug it?

Thanks
Daniel

**Comment by sfederow-velia** [comment]
I had a column in adata.obs that was named "label" and it appears this was interacting negatively with the li.multi.df_to_lr() function to cause an error similar to the above.  Once I renamed the "label" column from adata.obs it worked fine.  Might be good to rework the li.multi.df_to_lr() function to use some type of unique name with an underscore or something like that to prevent unintended overwrites.

**Comment by dbdimitrov** [comment]
Hi @sfederow-velia good point, 'label' is quite generic, I will rename it.
