### ISSUE TITLE
Clarification regarding hypothesis testing

### ISSUE THREAD

**Issue by inofechm** [saezlab/liana-py#54]
Hi Daniel,
Thank you for the fantastic work!
I was looking into applying the hypothesis-testing workflow onto some of my samples and was wondering if you could offer some clarification. 
When I run li.multi.df_to_lr after the DEA, is there any way to specify sampleID? If I have many different samples for each condition, is there a way for liana to ensure only sender and receiver cells from the same sample are used, as far as I see this approach is only used in the Tensor C2C or MOFA workflows with li.mt.rank_aggregate.by_sample, but not in this workflow. Would you recommend just filtering the adata to only include each sample one at a time before running liana? 
Thank you,
Ido

**Comment by dbdimitrov** [comment]
Hi @inofechm,

`li.multi.df_to_lr` is essentially oblivious to the samples, or in general the statistics in the dataframe that you provide. If you provide a dataframe which contains sample-level statistics and the anndata contains only a single sample, then it could do exactly that. 
Typically, I see it more as a function that essentially transforms aggregated stats (e.g. DEA pergene with PyDESeq2 as done in the tutorial) into ligand-receptor format. 

If you are interested in preserving information for the individual sample across conditions, MOFA and Tensor-cell2cell are, in my opinion, the way to go.

> Would you recommend just filtering the adata to only include each sample one at a time before running liana?

Currently QC is handled via `dc.get_pseudobulk` - essentially in this step will filter samples with low reads or numbers of cells for each cell type. Additionally, in the tutorial we filter the genes included in each cell type pseodobulk profile via `dc.filter_by_expr`. 
So, to answer the question, I would suggest to stick to the full object and consider checking the quality of genes and cells, individually for each cell type, as we essentially perform contrasts at the cell-type level. You can check this decoupler tutorial for more info on QC:
https://decoupler-py.readthedocs.io/en/latest/notebooks/pseudobulk.html#Generation-of-pseudo-bulk-profiles
It also provides plots which would give you an idea of the quality of samples per cell type.

Hope this helps.

**Comment by inofechm** [comment]
Thanks for the advice Daniel!
Will try both approaches.
