### ISSUE TITLE
Sort interactions names in `li.pl.tileplot` by the `orderby` argument 

### ISSUE THREAD

**Issue by PauBadiaM** [saezlab/liana-py#55]
Currently, interactions are not sorted in `li.pl.tileplot`, would be good to sort them by the `orderby` argument.

**Comment by PauBadiaM** [comment]
Maybe it would be good to specify a list of interactions with a predefined order, kinda like when you provide `ligand_complex` and `receptor_complex` but a new argument called `interaction`.

**Comment by dbdimitrov** [comment]
This is done now - to be covered in next release.
