### ISSUE TITLE
By default do not convert views to `csr_matrix` when building `MistyData`.

### ISSUE THREAD

**Issue by PauBadiaM** [saezlab/liana-py#57]
When building `MistyData` objects, the `.X` in each view is transformed into sparse `csr_matrix` format. This is not optimal to do in dense matrices with few zeros since the `csr_matrix` is going to consume more memory than its dense counterpart. I would maybe check the proportion of 0s and then decide.

**Comment by dbdimitrov** [comment]
I need to think about this, it's related to the matrices being in consistent format when modelling, and to avoid converting them multiple times - i.e. not so much about the efficiency of the size of the `MistyData` objects.
