### ISSUE TITLE
AttributeError: module 'liana.method' has no attribute 'build_prior_network'

### ISSUE THREAD

**Issue by qijt123** [saezlab/liana-py#59]
I ran the following code incorrectly:
`prior_graph = li.method.build_prior_network(input_pkn, input_scores, output_scores, verbose=True)`
The content of the error is:
`AttributeError: module 'liana.method' has no attribute 'build_prior_network'`

**Comment by dbdimitrov** [comment]
Hi @qijt123,

Which version of liana did you use? This should be available from any version >= 1.0.0.

**Comment by qijt123** [comment]
Hi @dbdimitrov ,
My version of liana is 0.1.9, which I installed with the following command:
`pip install liana`
How do I update to the latest version?

**Comment by dbdimitrov** [comment]
Hi @dbdimitrov,

You can install any of the more recent pre-releases (with @release name) or directly from the main branch.
`pip install git+https://github.com/saezlab/liana-py`

I will also make a release on pip soon

Daniel

**Comment by dbdimitrov** [comment]
I have now uploaded liana to pypi, you can simply install via `pip install liana`.

Feel free to open any other issues.
