### ISSUE TITLE
AttributeError: module 'corneto.methods.carnival' has no attribute 'select_mip_solver'

### ISSUE THREAD

**Issue by FADHLyemen** [saezlab/liana-py#64]
Hi 
I am trying to replicate the results in this link:
https://liana-py.readthedocs.io/en/stable/notebooks/targeted.html
but got this error:
AttributeError: module 'corneto.methods.carnival' has no attribute 'select_mip_solver'
when I run the same code in your link
```
df_res, problem = li.mt.find_causalnet(
    prior_graph,
    input_scores,
    output_scores,
    node_weights,
    # penalize (max_penalty) nodes with counts in less than 0.1 of the cells
    node_cutoff=0.1,
    max_penalty=1,
    # the penaly of those in > 0.1 prop of cells set to:
    min_penalty=0.01,
    edge_penalty=0.01,
    verbose=True,
    max_seconds=60*3
    )
```
I appreciate any suggestions.

**Comment by FADHLyemen** [comment]
this screen shot might help
![image](https://github.com/saezlab/liana-py/assets/23288387/0240e3cf-71aa-4cda-8ea3-c85b33e57af6)

**Comment by dbdimitrov** [comment]
Hey @FADHLyemen,

Please make sure that `cvxpy` and `cylp` are installed. I would also recommend installing `gurobipy` for a more efficient solver.

`pip install gurobipy cvxpy cylp`
You can also update corneto to it's latest version via pip - I just saw that I need to update the installation line in the tutorial
`pip install corneto --upgrade`

If these are installed, please share your session and I will debug from there :) 

Hope this helps.
Daniel

**Comment by FADHLyemen** [comment]
Thank you, @dbdimitrov 
I updated the corneto 
![image](https://github.com/saezlab/liana-py/assets/23288387/a5abac0c-f45c-4015-b455-12ea71e23021)
but I got a new error
SolverError: Solver 'GUROBI' failed. Try another solver, or solve with verbose=True for more information.

![image](https://github.com/saezlab/liana-py/assets/23288387/406bd24f-8c64-432e-8e46-913764ec0c24)

**Comment by FADHLyemen** [comment]
it only works when I add 
`solver='SCIPY'` to the function `li.mt.find_causalnet`

**Comment by dbdimitrov** [comment]
Hi @FADHLyemen,

My bad! Gurobi requires a license to work with "larger" problems. I will write a small guide how to get one soon. Scipy's Highs solver works also, it's slower!

**Comment by dbdimitrov** [comment]
Hi @FADHLyemen,

The way that  `find_causalpath` works is that it tries to find the smallest sign-coherent network that connects the input and output nodes. Where here the network and edges (I.e. the PPIs) are weighted according to the values in `node_weights`. In the tutorial, we use the proportion of cells expressing each gene per cell type, with genes (nodes) being expressed in low number of cells being assigned a higher penalty. In the case that a node is not in `node_weights` (I.e. a gene is missing in the data but present in the ppi prior knowledge), we assign an even higher penalty.

Here, the whole idea being quite simple - the path that connects the input (receptor) and output (tf) nodes has to be consistent with the sign of signalling, and the network itself prioritises nodes (and hence paths) that are observed in the data and are highly expressed. 

Hope this helps :)

**Comment by FADHLyemen** [comment]
@dbdimitrov, your explanation has been incredibly helpful.

However, what still perplexes me is how to interpret the color scheme for receptors, TFs, and proteins. Understanding the TF colors is straightforward, as they were computed through DEA, where red signifies an upregulation in stimulus compared to control.

Regarding the receptors, their values are derived from the interaction statistics. In this context, red implies a high ligand-receptor interaction, observed in both stimulus and control conditions.

Now, the challenge lies with the proteins. Given that their node weights are calculated solely from the stimulus data, discerning the significance of red versus blue isn't as clear-cut. It's evident that red doesn't directly signify an upregulation in stimulus versus control.

Considering these distinct value ranges for the three node types, your guidance in interpreting the color scheme would be greatly appreciated. Thank you.

**Comment by dbdimitrov** [comment]
Hi @FADHLyemen,

This is a really good question.

The way that node (protein) assignment sign works is that: according to the edges of the network corneto will make a call whether a node should be up- or down-regulated (this does not take the sign of perturbation from DEA).

As simple examples:

`A+ -> B+ -> C+` - here `B` will have a positive sign as the node needs to be upregulated for the positive (activation) edges that connect it to `A` and `C` to make sense.

`A+ -> B- -| C+` - here it will be negative because `B` is an inhibitor of `C` and it should be down for the path to make sense.

where `A` is the input nodes (e.g. receptors), `B` is part of the ppi network, `C` is the output node (TFs), `->` denotes activation and `-|` inhibition.

Hope this clarifies it :)

**Comment by dbdimitrov** [comment]
PS. One could use DEA info to assign according node weights to the PPI nodes such that the resultant network is most consistent with the changes across the conditions.

**Comment by dbdimitrov** [comment]
@FADHLyemen I will now close the issue. Happy to discuss any other point :)
