### ISSUE TITLE
Help understanding causal network output 

### ISSUE THREAD

**Issue by ebasto** [saezlab/liana-py#66]
Hello, 

I wanted to ask for clarification regarding the output of the causal network vignette "Hypothesis-testing for CCC & Downstream Signalling Networks".

Here is my current understanding:
 _**column name** (observed values when only a few) - description_
**source** - source node in the PPI, there are some values here that I don't understand ("_s","_pert_c0","_meas_c0","")
**source_type** (unmeasured,input) - are the input nodes the receptors that were identified in the previous step? are unmeasured genes that have no expression? or genes that are not part of that receptor group?
**source_weight** - not sure what this is, the example only has two values (0 and -4.66)
**source_pred_val** (1,0,-1) - node is upregulated, downregulated, is zero no differential expression?
**target** - target node in the PPI, there are some values here that I don't understand ("_s","_t","_meas_c0","")
**target_type** (unmeasured, output) - similar to "source_type" except "output" would be TFs?
**target_weight** - not sure what this is? the example has a few more values than "source_weight", they are all 0 or positive.
**target_pred_val** (1,-1) - node is upregulated, downregulated? no zeros in this one
**edge_type** (1,-1,0) - unsure what this is
**edge_pred_val**(1,-1) - whether the edge upregulates or downregulates the target node.

Thank you in advance!

Edgar

<img width="1040" alt="causal_network_output_top_rows" src="https://github.com/saezlab/liana-py/assets/12102945/625c5fbd-47c6-47fe-b33e-374f594ac9fe">

<img width="993" alt="causal_network_strange_values" src="https://github.com/saezlab/liana-py/assets/12102945/1e95cc07-a03c-4788-8dcd-ef5e090599c4">

**Comment by dbdimitrov** [comment]
Hi @ebasto,

These ("_s","_t","_meas_c0","") are just dummy variables used when setting the ILP problem to be solved.

`source_weight` and `target_weight` are the inputs provided to the causal net method (the "measured" nodes).

`edge type` is the type (sign) of interaction in the prior knowledge network, i.e. it is not predicted by the method.
e.g, A -> B, the edge_type is 1. If A=-1, source_pred_val=-1, edge_pred_val=-1, and target_pred_val=-1; 

Unmeasured nodes would be those that are not input or output - I.e. all other nodes (except the provided receptors or TFs in the tutorial).

All the rest you got correct :)

Thanks for pointing this out also. I realize that maybe it's a bit of a black box how it works. 

I will keep this issue open for now untol I provide a bit more details in the tutorial.
