### ISSUE TITLE
 li.multi.df_to_lr function gave gene Value error 

### ISSUE THREAD

**Issue by Hweeseon** [saezlab/liana-py#67]
Hi !
I was trying "Hypothesis-testing for CCC & Downstream Signalling Networks" tutorial.

During the "DEA to Ligand-Receptor Interactions" part I confront an issue. 

When I run,

lr_res = li.multi.df_to_lr(aadata,
                           dea_df=dea_df,
                           resource_name='consensus',
                           expr_prop=0.1, # calculated for adata as passed - used to filter interactions
                           groupby='cell_type2',
                           stat_keys=['stat', 'pvalue', 'padj'],
                           use_raw=False,
                           complex_col='stat', # NOTE: we use the Wald Stat to deal with complexes
                           verbose=True,
                           return_all_lrs=False,
                           )

I get warning that "all gene name values are not  are not valid obs/ var names or indices."
I checked, that aadata's var names has all genes.
I am attaching a screenshot of the situation.

![aaaaa](https://github.com/saezlab/liana-py/assets/113998108/445033da-e1f2-4e69-b14d-362fb52c1e42)
![bbbbb](https://github.com/saezlab/liana-py/assets/113998108/4bb6abc8-c562-4cc2-9380-97e6ce201a23)

I wonder what went wrong.

Best regards

**Comment by Hweeseon** [comment]
I'm attaching a screenshot of dea_df and aadata.var as well. 

![asdasd](https://github.com/saezlab/liana-py/assets/113998108/2adda7ee-ad2f-413e-a378-5a241cb5ea59)

**Comment by dbdimitrov** [comment]
Hey @Hweeseon,

Is it possible to upload a small subset of your data? I'm happy to debug it, as I can't see what could be an issue here. Besides, maybe there being no overlap between the resource (I.e. ligand and receptor genes) and your .var?

**Comment by Hweeseon** [comment]
Okay. I'll send subset data for this issue via e-mail to you.

**Comment by dbdimitrov** [comment]
@Hweeseon I will close the issue as it seemed to be related to the data itself as discussed via email.

Feel free to open new ones :)
