### ISSUE TITLE
The mouse resource are missing important interactions that should be possible to convert

### ISSUE THREAD

**Issue by johan-gson** [saezlab/liana-py#76]
**Describe the bug**
Hi and thanks for a nice tool. For example, Cxcl9 is missing as ligand in the database, while Cxcl10 is there, and they have many receptors in common. Converting CXCL9 to Cxcl9 should be doable? I'm guessing something has gone wrong and that many interactions are missing in the mouse data.

**To Reproduce**
Just look in the database

**Comment by dbdimitrov** [comment]
Hi @johan-gson,

Indeed, there are some interactions missing in the mouse data, very likely as their orthologues were missing from the mapping reference (homologene), that we used.

I plan to rebuilt the Consensus and MouseConsensus resources soon using orthologues from UniProt, and also provide a short tutorial for resource conversion.

I will keep you updated.

**Comment by johan-gson** [comment]
Thank you!

Best,

Johan

**Comment by dbdimitrov** [comment]
Hi @johan-gson, sorry for the delay, but I finally managed to implement orthology conversion that I'm happy with. 
Note the `min_evidence`  and `one_to_many` parameters, as depending on how strict you want to be with the prior and the mapping, might have a notable effect on the conversion.

https://liana-py.readthedocs.io/en/latest/notebooks/prior_knowledge.html#Obtain-Mouse-Homologs
