### ISSUE TITLE
Trouble with liana: 'liana.resource' has no attribute 'explode_complexes'

### ISSUE THREAD

**Issue by merlevede** [saezlab/liana-py#77]
Hello,

To make my analysis reproducible, I am creating an environment for my decoupler analyses and I am not able to run the liana quantification anymore. I am using the code described in the [doc](https://decoupler-py.readthedocs.io/en/latest/notebooks/bulk.html#Enrichment-of-ligand-receptor-interactions) to perform this analysis: 

```
liana_lr = ln.resource.select_resource()
liana_lr = ln.resource.explode_complexes(liana_lr)

# Create two new DataFrames, each containing one of the pairs of columns to be concatenated
df1 = liana_lr[['interaction', 'ligand']]
df2 = liana_lr[['interaction', 'receptor']]

# Rename the columns in each new DataFrame
df1.columns = ['interaction', 'genes']
df2.columns = ['interaction', 'genes']

# Concatenate the two new DataFrames
liana_lr = pd.concat([df1, df2], axis=0)
liana_lr['weight'] = 1

# Find duplicated rows
duplicates = liana_lr.duplicated()

# Remove duplicated rows
liana_lr = liana_lr[~duplicates]
```

I get the following error message: 

`'liana.resource' has no attribute 'explode_complexes'`

It seems that the code of liana select_resource was updated last month. I have the impression that the function ln.resource.explode_complexes is not accessible anymore.

Have you encountered a similar issue?

I am using the following versions:
decoupler           1.4.0
liana               1.0.3

Thanks for your help.

**Comment by dbdimitrov** [comment]
This should be resolved now with the latest update.
