### ISSUE TITLE
Error in function documentation / vignette

### ISSUE THREAD

**Issue by maximelepetit** [saezlab/liana-py#80]
Hello !
I'm currently running the Steady-state Ligand-Receptor inference vignette from (https://liana-py.readthedocs.io/en/latest/notebooks/basic_usage.html). 

When running li.pl.dotplot() and li.pl.tileplot() from the vignette i have the following errors : 
```
li.pl.dotplot(adata = adata,
              colour='lr_means',
              size='cellphone_pvals',
              inverse_size=True, # we inverse sign since we want small p-values to have large sizes
              source_labels=['CD34+', 'CD56+ NK', 'CD14+ Monocyte'],
              target_labels=['CD34+', 'CD56+ NK'],
              figure_size=(8, 7),
              # finally, since cpdbv2 suggests using a filter to FPs
              # we filter the pvals column to <= 0.05
              filter_fun=lambda x: x['cellphone_pvals'] <= 0.05,
              uns_key='cpdb_res' # uns_key to use, default is 'liana_res'
             )
```
Error : 
`TypeError: dotplot() got an unexpected keyword argument 'filter_fun'`

**I noticed that filter_fun parameter have been change as filter_lambda.**

I get the same type of error when running li.pl.tileplot() : 
```
my_plot = li.pl.tileplot(adata = adata,
                         # NOTE: fill & label need to exist for both
                         # ligand_ and receptor_ columns
                         fill='means',
                         label='props',
                         label_fun=lambda x: f'{x:.2f}',
                         top_n=10,
                         orderby='cellphone_pvals',
                         orderby_ascending=True,
                         source_labels=['CD34+', 'CD56+ NK', 'CD14+ Monocyte'],
                         target_labels=['CD34+', 'CD56+ NK'],
                         uns_key='cpdb_res', # NOTE: default is 'liana_res'
                         source_title='Ligand',
                         target_title='Receptor',
                         )
my_plot
```
Error : 
`TypeError: tileplot() got an unexpected keyword argument 'source_title'`

**source_title and target_title parameters have been removed** 

So i think this vignette and function documentation in the API are not up to date.

Thanks a lot. 

Best regards.

Maxime

**Comment by dbdimitrov** [comment]
Hi @maximelepetit,

I made some changes from the last update and the current version reflected in the docs.
I'm soon to make the latest release to pip, in the meantime you can install via github as:
pip install git+https://github.com/saezlab/liana-py

**Comment by maximelepetit** [comment]
Thanks a lot for the quick reply !!
