### ISSUE TITLE
Magnitude ranks identical in same sample across cell type

### ISSUE THREAD

**Issue by ShadHOH** [saezlab/liana-py#89]
Thank you for this great tool,

I have been trying to get the Liana-c2c-tensor setup to work for our data to compare CCC two treatments. Although I am able to successfully run the 'PBMC context factorization' tutorial, when examining the context loadings in our own data, I do not find any noticeable difference across both treatments. This was rather unexpected as our two conditions have shown considerable changes in DEG, so absolutely no change in CCC seems odd. To verify if this was biological or perhaps a technical issue, I repeated this for multiple condition comparisons, tried with different parameters, and even tried on different datasets - same result. 

To examine the problem, I recently took a look at the top 30 sorted magnitude ranks and noticed that the same cell types from the same sample had exactly the same magnitude when the role of sender and receiver cell is reversed (also, note that the dataset contains 6 abundant cell types but only 2 are consistently showing). I have attached an image showing the results to better convey this. The results indicate to me something has gone wrong. I am unsure what may have caused it. Do you have any suggestions on how to troubleshoot this?

![image](https://github.com/saezlab/liana/assets/89731636/28d88571-4e32-49ec-a9f9-01ee7c516e6b)

Code used to calculate ranks:

`li.mt.rank_aggregate.by_sample(
    adata,
    groupby=groupby,
    sample_key=sample_key, # sample key by which we which to loop
    use_raw=False,
    verbose=True, # use 'full' to show all verbose information
    n_perms=100, # reduce permutations for speed
    return_all_lrs=True, # return all LR values
    )`

**Comment by dbdimitrov** [comment]
Hi @ShadHOH,

Thanks for using LIANA. :)
 
Though I am unable to reproduce your issue with the information you provided.

I'd be happy to explore further but I would need the liana version, the code to produce the screenshot you attached, and ideally a small subset of you data that I can test myself.
