### ISSUE TITLE
code li.pl.dotplot output an disappointing result

### ISSUE THREAD

**Issue by Fanyu000** [saezlab/liana-py#95]
Hi, I did liana on several samples aggregrated dataset. the dataset information of the dataset
![image](https://github.com/saezlab/liana-py/assets/163302953/6d3ad781-056c-4c87-927f-37cf26668849)

Then I follow the tutorial, using cellphonedb to acquire receptor-ligand interaction information
![image](https://github.com/saezlab/liana-py/assets/163302953/e8ea5d6e-702d-4f6e-99b6-873868fb9af2)

So next step I want to visualize the result with 'li.pl.dotplot' but the output result  is messy.
![image](https://github.com/saezlab/liana-py/assets/163302953/df1be763-44f5-4bc9-a828-9d3fedae6673)

What's wrong with my process? I think there's detail I ignore but I don't know how to prioritise to make the final result clear enough to know the receptor-ligand pair with corresponding cell type.

**Comment by Fanyu000** [comment]
![image](https://github.com/saezlab/liana-py/assets/163302953/882850c8-b713-4b3b-99ee-5f77f6e5a346)

**Comment by Marwansha** [comment]
i guess you need to specify the number of interactions you need to show

"top_n=10,"

**Comment by dbdimitrov** [comment]
Hi @Fanyu000, likely the answer by @Marwansha would be one solution. However, I cannot give you any better advice if you don't share the code used to get to this point.

Daniel

**Comment by Fanyu000** [comment]
@Marwansha  thanks, it works.

**Comment by Fanyu000** [comment]
@dbdimitrov the answer offered by @Marwansha solves the problem. 
![image](https://github.com/saezlab/liana-py/assets/163302953/eb81694f-b1f2-441f-a263-0e00aa874ebb)

Can I communicate with you for more details？

Fanyu

**Comment by dbdimitrov** [comment]
Hi @Fanyu000,

Sure. My email is my daniel.dimitrov[÷÷÷]uni-heidelberg.de
