### ISSUE TITLE
ValueError: Please check if appropriate organism/ID type was provided! 

### ISSUE THREAD

**Issue by anke-king** [saezlab/liana-py#97]
I get this error and it lists a number of genes that are not found in the data, although they are in var names (I checked). So I have no idea why this error occurs?

Also im trying to assess communication between mouse and human cells, so what would I have to specify as organism?

Thanks for the help!

**Comment by dbdimitrov** [comment]
Hi @anke-king,

Can you please show the adata.var of your data and how do you specify the resource which liana is using (e.g. via `resource_name`)?

**Comment by anke-king** [comment]
I used the default, so not specifying anything (trying to follow your tutorial)
Here is a short subset of my var_names:

print(adata_human_mouse.var_names[adata_human_mouse.var_names.str.startswith("CCL")]):

Index(['CCL1', 'CCL11', 'CCL12', 'CCL15', 'CCL15-CCL14', 'CCL17', 'CCL22',
       'CCL23', 'CCL24', 'CCL28', 'CCL3', 'CCL4', 'CCL4L2', 'CCL5', 'CCL7',
       'CCL8'],
      dtype='object')

some of these are required in the error message and said not to be in var_names although they are there?
Should I specify a different resource? I tried mouseconensus but the same error occurs (also all my gene names are in human format).

**Comment by dbdimitrov** [comment]
Hi @anke-king, 

If you can share a subset of your data and the function you were using from liana, I can debug it on my end.

Daniel

**Comment by soniyalama** [comment]
You should add use_raw = False

**Comment by Wulei26** [comment]
I encountered the same problem！！
This is my error message:
testdata =  li.method.cellphonedb.__call__(adata = AnnData, groupby = "cell_type_need")
/public/home/wulei/miniconda3/envs/liana/lib/python3.12/site-packages/anndata/_core/anndata.py:430: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
/public/home/wulei/miniconda3/envs/liana/lib/python3.12/site-packages/pandas/core/indexing.py:1857: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/public/home/wulei/miniconda3/envs/liana/lib/python3.12/site-packages/liana/method/_Method.py", line 247, in __call__
    liana_res = liana_pipe(adata=adata,
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/wulei/miniconda3/envs/liana/lib/python3.12/site-packages/liana/method/_liana_pipe.py", line 144, in liana_pipe
    assert_covered(np.union1d(np.unique(resource["ligand"]),
  File "/public/home/wulei/miniconda3/envs/liana/lib/python3.12/site-packages/liana/method/_pipe_utils/_pre.py", line 56, in assert_covered
    raise ValueError(msg + f" [{x_missing}] missing from {superset_name}")
ValueError: Please check if appropriate organism/ID type was provided! Allowed proportion (0.98) of missing resource elements exceeded (1.00). Too few features from the resource were found in the data.
How can I solve this？

**Comment by dbdimitrov** [comment]
Hi @Wulei26, likely you need to pass `use_raw = False` :)
